import type { EducationProgram } from '../../game/core/types'

export const EDUCATION_PROGRAMS: EducationProgram[] = [
  {
    id: 'community-college-basics',
    title: 'Community College Basics',
    description: 'A starter post-high-school track that improves credibility, routine, and general knowledge without demanding a full degree path.',
    durationMonths: 3,
    totalCost: 360,
    reputationRequired: 0,
    monthlyStress: 2,
    monthlyEnergy: 4,
    knowledgeReward: 2,
    reputationReward: 1,
  },
  {
    id: 'sales-diploma',
    title: 'Retail Sales Diploma',
    description: 'Longer than a short course, but cheaper than brute-forcing your way into customer-facing work with pure hustle.',
    durationMonths: 4,
    totalCost: 520,
    reputationRequired: 1,
    monthlyStress: 3,
    monthlyEnergy: 5,
    knowledgeReward: 3,
    reputationReward: 1,
    certificationReward: 'sales-course',
  },
  {
    id: 'finance-night-school',
    title: 'Finance Night School',
    description: 'Accounting, market basics, and enough financial literacy to support more serious investing and analyst work.',
    durationMonths: 5,
    totalCost: 1200,
    reputationRequired: 3,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 5,
    reputationReward: 2,
    certificationReward: 'finance-cert',
  },
  {
    id: 'property-operations',
    title: 'Property Operations Certificate',
    description: 'A slower, more structured route into leases, maintenance systems, and real-estate operations.',
    durationMonths: 5,
    totalCost: 900,
    reputationRequired: 3,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 4,
    reputationReward: 2,
    certificationReward: 'landlord-license',
  },
  {
    id: 'software-apprenticeship',
    title: 'Software Apprenticeship',
    description: 'A real time sink, but it creates the strongest jump in long-run earning power if you can survive the runway hit.',
    durationMonths: 6,
    totalCost: 1750,
    reputationRequired: 5,
    monthlyStress: 5,
    monthlyEnergy: 7,
    knowledgeReward: 7,
    reputationReward: 3,
    certificationReward: 'coding-bootcamp',
  },
]

export const EDUCATION_PROGRAM_MAP = Object.fromEntries(EDUCATION_PROGRAMS.map((program) => [program.id, program])) as Record<string, EducationProgram>
