import type { EducationProgram } from '../../game/core/types'

const image = (imageUrl: string, imageAlt: string) => ({ imageUrl, imageAlt })

export const EDUCATION_PROGRAMS: EducationProgram[] = [
  {
    id: 'community-college-basics',
    title: 'Community College Basics',
    description: 'A starter structured study path that improves routine, credibility, and general knowledge without asking for a full degree commitment yet.',
    durationMonths: 3,
    totalCost: 900,
    reputationRequired: 0,
    monthlyStress: 2,
    monthlyEnergy: 4,
    knowledgeReward: 2,
    reputationReward: 1,
    educationTier: 'certificate',
    careerField: 'operations-logistics',
    trackTags: ['foundation', 'general', 'entry'],
    recommendedProgramIds: ['logistics-diploma', 'sales-diploma', 'healthcare-admin-diploma'],
    ...image('https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80', 'Students studying together on a college campus'),
  },
  {
    id: 'finance-night-school',
    title: 'Finance Night School',
    description: 'Accounting basics, spreadsheets, and enough structure to make finance work feel reachable instead of distant.',
    durationMonths: 3,
    totalCost: 1800,
    reputationRequired: 3,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 4,
    reputationReward: 2,
    educationTier: 'certificate',
    careerField: 'finance-accounting',
    trackTags: ['finance', 'night-school', 'bridge'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    certificationReward: 'finance-cert',
    ...image('https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80', 'Finance coursework with charts and a calculator'),
  },
  {
    id: 'property-operations',
    title: 'Property Operations Certificate',
    description: 'A structured route into leases, maintenance systems, and the practical side of property work.',
    durationMonths: 4,
    totalCost: 1650,
    reputationRequired: 3,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 4,
    reputationReward: 2,
    educationTier: 'certificate',
    careerField: 'property-real-estate',
    trackTags: ['property', 'operations', 'bridge'],
    recommendedProgramIds: ['real-estate-diploma', 'property-bachelor'],
    certificationReward: 'landlord-license',
    ...image('https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80', 'Apartment building and maintenance clipboard'),
  },
  {
    id: 'sales-diploma',
    title: 'Retail Sales Diploma',
    description: 'Longer than a short certificate, but much easier than trying to bluff your way into stronger selling roles.',
    durationMonths: 5,
    totalCost: 2800,
    reputationRequired: 1,
    monthlyStress: 3,
    monthlyEnergy: 5,
    knowledgeReward: 3,
    reputationReward: 1,
    educationTier: 'diploma',
    careerField: 'sales-marketing',
    trackTags: ['sales', 'closing', 'customer'],
    recommendedProgramIds: ['marketing-bachelor'],
    certificationReward: 'sales-course',
    ...image('https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80', 'Small group training session in a bright office'),
  },
  {
    id: 'software-apprenticeship',
    title: 'Software Apprenticeship',
    description: 'A heavy commitment, but one of the clearest structured routes from support and QA work into real technical jobs.',
    durationMonths: 8,
    totalCost: 5400,
    reputationRequired: 5,
    monthlyStress: 5,
    monthlyEnergy: 7,
    knowledgeReward: 7,
    reputationReward: 3,
    educationTier: 'diploma',
    careerField: 'technology-product',
    trackTags: ['software', 'apprenticeship', 'career-switch'],
    recommendedProgramIds: ['software-bachelor', 'product-masters'],
    certificationReward: 'coding-bootcamp',
    ...image('https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80', 'Software apprentice coding at a laptop'),
  },
  {
    id: 'logistics-diploma',
    title: 'Logistics Coordination Diploma',
    description: 'A structured route into dispatch, operations reporting, and the cleaner side of fulfillment work.',
    durationMonths: 6,
    totalCost: 3200,
    reputationRequired: 2,
    monthlyStress: 4,
    monthlyEnergy: 5,
    knowledgeReward: 4,
    reputationReward: 2,
    educationTier: 'diploma',
    careerField: 'operations-logistics',
    trackTags: ['logistics', 'dispatch', 'operations'],
    recommendedProgramIds: ['operations-bachelor', 'operations-masters'],
    certificationReward: 'route-planning-cert',
    ...image('https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80', 'Dispatch worker coordinating logistics on multiple screens'),
  },
  {
    id: 'accounting-diploma',
    title: 'Accounting Diploma',
    description: 'A more serious bookkeeping and payroll path that starts to qualify you for cleaner finance roles instead of just finance-adjacent work.',
    durationMonths: 7,
    totalCost: 4600,
    reputationRequired: 4,
    monthlyStress: 5,
    monthlyEnergy: 6,
    knowledgeReward: 6,
    reputationReward: 2,
    educationTier: 'diploma',
    careerField: 'finance-accounting',
    trackTags: ['accounting', 'bookkeeping', 'payroll'],
    recommendedProgramIds: ['finance-bachelor', 'finance-masters'],
    certificationReward: 'bookkeeping-cert',
    ...image('https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&w=1200&q=80', 'Accounting desk with invoices and calculator'),
  },
  {
    id: 'real-estate-diploma',
    title: 'Real Estate Operations Diploma',
    description: 'Leasing, work orders, tenant systems, and the practical side of running buildings as a business.',
    durationMonths: 6,
    totalCost: 3900,
    reputationRequired: 4,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 5,
    reputationReward: 2,
    educationTier: 'diploma',
    careerField: 'property-real-estate',
    trackTags: ['property', 'leasing', 'operations'],
    recommendedProgramIds: ['property-bachelor', 'property-masters'],
    certificationReward: 'property-maintenance-cert',
    ...image('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80', 'Modern apartment building exterior'),
  },
  {
    id: 'healthcare-admin-diploma',
    title: 'Healthcare Administration Diploma',
    description: 'Patient flow, records, scheduling, billing, and the office discipline that higher clinic roles actually want.',
    durationMonths: 6,
    totalCost: 4200,
    reputationRequired: 3,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 5,
    reputationReward: 2,
    educationTier: 'diploma',
    careerField: 'healthcare-administration',
    trackTags: ['healthcare', 'admin', 'operations'],
    recommendedProgramIds: ['healthcare-bachelor', 'healthcare-masters'],
    certificationReward: 'healthcare-admin-cert',
    ...image('https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80', 'Healthcare administration desk with clipboard and tablet'),
  },
  {
    id: 'operations-bachelor',
    title: 'Bachelor of Operations Management',
    description: 'A long, expensive route into systems, planning, throughput, and the cleaner upper tiers of logistics work.',
    durationMonths: 14,
    totalCost: 10800,
    reputationRequired: 6,
    monthlyStress: 5,
    monthlyEnergy: 6,
    knowledgeReward: 10,
    reputationReward: 4,
    educationTier: 'bachelor',
    careerField: 'operations-logistics',
    trackTags: ['operations', 'management', 'degree'],
    programRequirements: ['logistics-diploma'],
    recommendedProgramIds: ['operations-masters'],
    ...image('https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80', 'Warehouse operations coursework and logistics planning'),
  },
  {
    id: 'finance-bachelor',
    title: 'Bachelor of Finance',
    description: 'This is where finance becomes expensive and slow, but also turns into a real analyst and upper-office lane.',
    durationMonths: 15,
    totalCost: 13600,
    reputationRequired: 7,
    monthlyStress: 6,
    monthlyEnergy: 7,
    knowledgeReward: 12,
    reputationReward: 4,
    educationTier: 'bachelor',
    careerField: 'finance-accounting',
    trackTags: ['finance', 'bachelor', 'analysis'],
    programRequirements: ['accounting-diploma'],
    certificationRequirements: ['finance-cert'],
    recommendedProgramIds: ['finance-masters'],
    ...image('https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80', 'Finance classroom and charts on a laptop'),
  },
  {
    id: 'property-bachelor',
    title: 'Bachelor of Property Operations',
    description: 'A slower, formal route into asset coordination, portfolio reporting, and the cleaner side of real-estate careers.',
    durationMonths: 14,
    totalCost: 11800,
    reputationRequired: 7,
    monthlyStress: 5,
    monthlyEnergy: 6,
    knowledgeReward: 10,
    reputationReward: 4,
    educationTier: 'bachelor',
    careerField: 'property-real-estate',
    trackTags: ['property', 'asset-management', 'degree'],
    programRequirements: ['real-estate-diploma'],
    certificationRequirements: ['landlord-license'],
    recommendedProgramIds: ['property-masters'],
    ...image('https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80', 'Residential property operations coursework'),
  },
  {
    id: 'marketing-bachelor',
    title: 'Bachelor of Marketing & Growth',
    description: 'Longer and pricier than the diploma path, but it unlocks cleaner campaign and growth roles with much better upside.',
    durationMonths: 13,
    totalCost: 9800,
    reputationRequired: 6,
    monthlyStress: 5,
    monthlyEnergy: 6,
    knowledgeReward: 9,
    reputationReward: 4,
    educationTier: 'bachelor',
    careerField: 'sales-marketing',
    trackTags: ['marketing', 'growth', 'degree'],
    programRequirements: ['sales-diploma'],
    certificationRequirements: ['sales-course'],
    recommendedProgramIds: [],
    ...image('https://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&w=1200&q=80', 'Marketing team workshop with notes on a glass wall'),
  },
  {
    id: 'software-bachelor',
    title: 'Bachelor of Software Systems',
    description: 'A long, expensive track that turns tech from freelance side money into a real long-term career lane.',
    durationMonths: 16,
    totalCost: 15200,
    reputationRequired: 7,
    monthlyStress: 6,
    monthlyEnergy: 7,
    knowledgeReward: 13,
    reputationReward: 4,
    educationTier: 'bachelor',
    careerField: 'technology-product',
    trackTags: ['software', 'systems', 'degree'],
    programRequirements: ['software-apprenticeship'],
    certificationRequirements: ['coding-bootcamp'],
    recommendedProgramIds: ['product-masters'],
    ...image('https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Developer classroom and code on projected screen'),
  },
  {
    id: 'healthcare-bachelor',
    title: 'Bachelor of Healthcare Administration',
    description: 'A formal path into office management, compliance, and higher-trust healthcare admin leadership.',
    durationMonths: 15,
    totalCost: 12800,
    reputationRequired: 6,
    monthlyStress: 5,
    monthlyEnergy: 6,
    knowledgeReward: 11,
    reputationReward: 4,
    educationTier: 'bachelor',
    careerField: 'healthcare-administration',
    trackTags: ['healthcare', 'administration', 'degree'],
    programRequirements: ['healthcare-admin-diploma'],
    certificationRequirements: ['healthcare-admin-cert'],
    recommendedProgramIds: ['healthcare-masters'],
    ...image('https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80', 'Healthcare management study desk with documents and tablet'),
  },
  {
    id: 'operations-masters',
    title: 'Master of Operations Systems',
    description: 'An advanced route into network-scale logistics leadership, forecasting, and the upper end of operations management.',
    durationMonths: 10,
    totalCost: 16400,
    reputationRequired: 10,
    monthlyStress: 6,
    monthlyEnergy: 7,
    knowledgeReward: 10,
    reputationReward: 5,
    educationTier: 'master',
    careerField: 'operations-logistics',
    trackTags: ['operations', 'advanced', 'leadership'],
    programRequirements: ['operations-bachelor'],
    certificationRequirements: ['operations-systems-cert'],
    recommendedProgramIds: [],
    ...image('https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80', 'Advanced logistics operations planning session'),
  },
  {
    id: 'finance-masters',
    title: 'Master of Corporate Finance',
    description: 'Very expensive, very slow, and exactly the kind of degree that starts unlocking elite finance work instead of just better clerical work.',
    durationMonths: 10,
    totalCost: 18800,
    reputationRequired: 11,
    monthlyStress: 7,
    monthlyEnergy: 7,
    knowledgeReward: 12,
    reputationReward: 5,
    educationTier: 'master',
    careerField: 'finance-accounting',
    trackTags: ['finance', 'advanced', 'leadership'],
    programRequirements: ['finance-bachelor'],
    certificationRequirements: ['finance-cert', 'payroll-cert'],
    recommendedProgramIds: [],
    ...image('https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80', 'Advanced finance study materials on a conference table'),
  },
  {
    id: 'property-masters',
    title: 'Master of Asset Management',
    description: 'A narrow but powerful advanced property route for portfolio operations, capital planning, and cleaner upper-tier real-estate work.',
    durationMonths: 9,
    totalCost: 17200,
    reputationRequired: 10,
    monthlyStress: 6,
    monthlyEnergy: 6,
    knowledgeReward: 11,
    reputationReward: 5,
    educationTier: 'master',
    careerField: 'property-real-estate',
    trackTags: ['property', 'asset-management', 'advanced'],
    programRequirements: ['property-bachelor'],
    certificationRequirements: ['landlord-license'],
    recommendedProgramIds: [],
    ...image('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80', 'Property asset management coursework and buildings'),
  },
  {
    id: 'product-masters',
    title: 'Master of Product Strategy',
    description: 'A brutally expensive upper path that finally qualifies you for the cleaner product and startup operator roles.',
    durationMonths: 10,
    totalCost: 19400,
    reputationRequired: 11,
    monthlyStress: 7,
    monthlyEnergy: 7,
    knowledgeReward: 12,
    reputationReward: 5,
    educationTier: 'master',
    careerField: 'technology-product',
    trackTags: ['product', 'strategy', 'advanced'],
    programRequirements: ['software-bachelor'],
    certificationRequirements: ['coding-bootcamp', 'support-systems-cert'],
    recommendedProgramIds: [],
    ...image('https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80', 'Product strategy workshop with charts and laptop'),
  },
  {
    id: 'healthcare-masters',
    title: 'Master of Healthcare Compliance',
    description: 'Advanced policy, risk, and operations work for players who want the high-trust top end of healthcare administration.',
    durationMonths: 10,
    totalCost: 17800,
    reputationRequired: 10,
    monthlyStress: 6,
    monthlyEnergy: 7,
    knowledgeReward: 11,
    reputationReward: 5,
    educationTier: 'master',
    careerField: 'healthcare-administration',
    trackTags: ['healthcare', 'compliance', 'advanced'],
    programRequirements: ['healthcare-bachelor'],
    certificationRequirements: ['compliance-admin-cert'],
    recommendedProgramIds: [],
    ...image('https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80', 'Healthcare compliance paperwork and tablet'),
  },
]

export const EDUCATION_PROGRAM_MAP = Object.fromEntries(EDUCATION_PROGRAMS.map((program) => [program.id, program])) as Record<string, EducationProgram>
