import type { EducationProgram } from '../../game/core/types'

const image = (imageUrl: string, imageAlt: string) => ({ imageUrl, imageAlt })

export const EDUCATION_PROGRAMS: EducationProgram[] = [
  {
    id: 'community-college-basics',
    title: 'Community College Basics',
    description: 'A starter post-high-school track that improves credibility, routine, and general knowledge without demanding a full degree path.',
    durationMonths: 3,
    totalCost: 360,
    reputationRequired: 0,
    monthlyStress: 2,
    monthlyEnergy: 4,
    knowledgeReward: 2,
    reputationReward: 1,
    ...image('https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80', 'Students studying together on a college campus'),
  },
  {
    id: 'sales-diploma',
    title: 'Retail Sales Diploma',
    description: 'Longer than a short course, but much easier than trying to bluff your way into better sales work.',
    durationMonths: 4,
    totalCost: 480,
    reputationRequired: 1,
    monthlyStress: 3,
    monthlyEnergy: 5,
    knowledgeReward: 3,
    reputationReward: 1,
    certificationReward: 'sales-course',
    ...image('https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80', 'Small group training session in a bright office'),
  },
  {
    id: 'finance-night-school',
    title: 'Finance Night School',
    description: 'Accounting, market basics, and enough structure to make finance work feel reachable instead of distant.',
    durationMonths: 5,
    totalCost: 980,
    reputationRequired: 3,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 5,
    reputationReward: 2,
    certificationReward: 'finance-cert',
    ...image('https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80', 'Finance coursework with charts and a calculator'),
  },
  {
    id: 'property-operations',
    title: 'Property Operations Certificate',
    description: 'A slower, more structured route into leases, maintenance systems, and the practical side of property work.',
    durationMonths: 5,
    totalCost: 760,
    reputationRequired: 3,
    monthlyStress: 4,
    monthlyEnergy: 6,
    knowledgeReward: 4,
    reputationReward: 2,
    certificationReward: 'landlord-license',
    ...image('https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80', 'Apartment building and maintenance clipboard'),
  },
  {
    id: 'software-apprenticeship',
    title: 'Software Apprenticeship',
    description: 'A heavy commitment, but one of the clearest ways to change your long-term income path.',
    durationMonths: 6,
    totalCost: 1480,
    reputationRequired: 5,
    monthlyStress: 5,
    monthlyEnergy: 7,
    knowledgeReward: 7,
    reputationReward: 3,
    certificationReward: 'coding-bootcamp',
    ...image('https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80', 'Software apprentice coding at a laptop'),
  },
]

export const EDUCATION_PROGRAM_MAP = Object.fromEntries(EDUCATION_PROGRAMS.map((program) => [program.id, program])) as Record<string, EducationProgram>
