import type { Stock } from '../../game/core/types'

const image = (imageUrl: string, imageAlt: string) => ({ imageUrl, imageAlt })

export const BASE_MARKET: Stock[] = [
  { symbol: 'BYTE', name: 'ByteForge AI', sector: 'tech', assetType: 'stock', thesis: 'High-beta AI platform name with fast earnings reactions.', price: 42, drift: 0.026, volatility: 0.17, dividend: 0.05, change: 0, earningsMonth: 3, ...image('https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1400&q=80', 'Developer workstation with code on screen representing an AI software company') },
  { symbol: 'BRIX', name: 'Brix Urban REIT', sector: 'real-estate', assetType: 'stock', thesis: 'Yield-heavy real-estate vehicle tied to rate pressure and rent demand.', price: 18, drift: 0.016, volatility: 0.08, dividend: 0.14, change: 0, earningsMonth: 2, ...image('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80', 'Urban apartment building representing a real-estate trust') },
  { symbol: 'HEAL', name: 'Healix Bio', sector: 'health', assetType: 'stock', thesis: 'Health-growth name that trades hard on trial and earnings headlines.', price: 31, drift: 0.018, volatility: 0.1, dividend: 0.08, change: 0, earningsMonth: 1, ...image('https://images.unsplash.com/photo-1532187643603-ba119ca4109e?auto=format&fit=crop&w=1400&q=80', 'Scientist working in a biotech laboratory') },
  { symbol: 'SODA', name: 'Soda Street Brands', sector: 'consumer', assetType: 'stock', thesis: 'Steadier consumer brand with modest dividends and demand sensitivity.', price: 15, drift: 0.012, volatility: 0.07, dividend: 0.09, change: 0, earningsMonth: 4, ...image('https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80', 'Grocery aisle with packaged consumer products') },
  { symbol: 'GRID', name: 'Gridline Utilities', sector: 'energy', assetType: 'stock', thesis: 'Defensive utility-style payer that holds up better in bad tape.', price: 27, drift: 0.019, volatility: 0.09, dividend: 0.12, change: 0, earningsMonth: 6, ...image('https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1400&q=80', 'High-voltage power lines at sunset representing utility infrastructure') },
  { symbol: 'NOVA', name: 'Nova Mobility', sector: 'mobility', assetType: 'stock', thesis: 'Growth mobility name with wider swings on sentiment and execution.', price: 23, drift: 0.024, volatility: 0.14, dividend: 0.04, change: 0, earningsMonth: 5, ...image('https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80', 'Modern car on the road representing a mobility company') },
  { symbol: 'CITY', name: 'CityCore Index ETF', sector: 'index', assetType: 'etf', thesis: 'Broad-market ETF that smooths single-name risk across the city economy.', price: 34, drift: 0.017, volatility: 0.06, dividend: 0.1, change: 0, expenseRatio: 0.003, ...image('https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1400&q=80', 'City skyline and busy streets representing a broad market index fund') },
  { symbol: 'YIELD', name: 'Cashflow Dividend ETF', sector: 'dividend', assetType: 'etf', thesis: 'Income-focused ETF with steadier payouts and lower upside.', price: 26, drift: 0.013, volatility: 0.05, dividend: 0.15, change: 0, expenseRatio: 0.004, ...image('https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=1400&q=80', 'Calculator, notes, and cash representing steady income investing') },
  { symbol: 'SPRK', name: 'Frontier Growth ETF', sector: 'growth', assetType: 'etf', thesis: 'Aggressive growth basket that captures momentum without single-name blowups.', price: 29, drift: 0.021, volatility: 0.09, dividend: 0.05, change: 0, expenseRatio: 0.005, ...image('https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=80', 'Fast-moving startup team representing aggressive growth investing') },
]
