import type { PersonalAction } from '../../game/core/types'

const image = (imageUrl: string, imageAlt: string) => ({ imageUrl, imageAlt })

export const PERSONAL_ACTIONS: PersonalAction[] = [
  {
    id: 'sleep-in',
    title: 'Sleep In',
    category: 'recovery',
    cashCost: 0,
    actionCost: 1,
    description: 'Block the alarms, stay off the grind for a day, and give your body the easiest recovery week available.',
    oncePerWeek: true,
    effects: { stress: -10, energy: 8, health: 2 },
    ...image('https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', 'Sunlit bed with white sheets and pillows'),
  },
  {
    id: 'nature-walk',
    title: 'Nature Walk',
    category: 'recovery',
    cashCost: 8,
    actionCost: 1,
    description: 'Cheap outdoor time resets your head a bit, but it still costs time and a little spending money.',
    oncePerWeek: true,
    effects: { stress: -7, energy: 4, health: 2 },
    ...image('https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80', 'Path through a quiet green park at golden hour'),
  },
  {
    id: 'stay-in',
    title: 'Stay In',
    category: 'recovery',
    cashCost: 4,
    actionCost: 1,
    description: 'Keep the lights low, keep spending near zero, and use a quiet day to recover some energy.',
    oncePerWeek: true,
    effects: { stress: -6, energy: 5 },
    ...image('https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80', 'Calm small room with lamp light and a made bed'),
  },
  {
    id: 'movie-night',
    title: 'Game / Movie Night',
    category: 'leisure',
    cashCost: 18,
    actionCost: 1,
    description: 'A low-pressure night off. It is not productive, and that is the point.',
    oncePerWeek: true,
    effects: { stress: -9, energy: 3 },
    ...image('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80', 'Dark room with projector light and relaxed seating'),
  },
  {
    id: 'cheap-treat',
    title: 'Cheap Treat',
    category: 'leisure',
    cashCost: 12,
    actionCost: 1,
    description: 'A small indulgence. Not a life fix, just a way to make the week feel a little more human.',
    oncePerWeek: true,
    effects: { stress: -6, health: 1 },
    ...image('https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=1200&q=80', 'Pastry and coffee on a cafe table'),
  },
  {
    id: 'day-off-out',
    title: 'Day Off Out',
    category: 'leisure',
    cashCost: 35,
    actionCost: 1,
    description: 'A real break away from the routine. Expensive early, but it can stop a rough stretch from compounding.',
    oncePerWeek: true,
    effects: { stress: -12, energy: 2, reputation: 1 },
    ...image('https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80', 'Busy city street with people out enjoying the day'),
  },
  {
    id: 'call-family',
    title: 'Call Family',
    category: 'social',
    cashCost: 0,
    actionCost: 1,
    description: 'A free reset that helps emotionally without pretending it solves your finances.',
    oncePerWeek: true,
    effects: { stress: -5, reputation: 1 },
    ...image('https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80', 'Person talking on a phone near a window'),
  },
  {
    id: 'meet-friend',
    title: 'Meet A Friend',
    category: 'social',
    cashCost: 15,
    actionCost: 1,
    description: 'A little money and time for a more human week. Keeps your reputation moving without turning social time into a grind.',
    oncePerWeek: true,
    effects: { stress: -7, energy: 2, reputation: 1 },
    contactId: 'recruiter',
    ...image('https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80', 'Two friends talking outside a cafe'),
  },
  {
    id: 'community-dinner',
    title: 'Community Dinner',
    category: 'social',
    cashCost: 5,
    actionCost: 1,
    description: 'A cheap local reset that feeds you, lowers stress, and can quietly open social leads later.',
    oncePerWeek: true,
    effects: { stress: -6, health: 2 },
    storyFlag: 'neighbor-network-open',
    ...image('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80', 'Long dinner table with shared food and people gathering'),
  },
]

export const PERSONAL_ACTION_MAP = Object.fromEntries(PERSONAL_ACTIONS.map((action) => [action.id, action])) as Record<string, PersonalAction>
