import type { Course, Gig, Job, SideJob, Upgrade } from '../../game/core/types'

const image = (imageUrl: string, imageAlt: string) => ({ imageUrl, imageAlt })

const JOB_IMAGES = {
  cleaning: image('https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80', 'Custodian cleaning a modern hallway'),
  labor: image('https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80', 'Worker carrying boxes in a warehouse'),
  cafe: image('https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80', 'Barista working behind a cafe counter'),
  sales: image('https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80', 'Retail worker helping a customer in a store'),
  office: image('https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80', 'Office worker sitting at a desk with a laptop and notes'),
  logistics: image('https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80', 'Dispatch worker coordinating logistics on multiple screens'),
  hospitality: image('https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80', 'Hotel front desk worker helping a guest'),
  analyst: image('https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80', 'Financial analyst reviewing charts on a desk'),
  property: image('https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80', 'Property manager standing outside an apartment building'),
  startup: image('https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80', 'Startup team collaborating around a table'),
} as const

const SKILL_IMAGES = {
  sales: image('https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Instructor coaching a student in a sales workshop'),
  finance: image('https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80', 'Laptop showing financial charts and spreadsheets'),
  property: image('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80', 'Modern apartment building exterior'),
  coding: image('https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80', 'Developer coding at a workstation'),
  mobility: image('https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=80', 'Scooter parked on an urban street'),
  tools: image('https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80', 'Hand tools laid out on a workbench'),
  crm: image('https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80', 'Property management dashboard on a laptop'),
  emergency: image('https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=1200&q=80', 'Budget notebook with cash and calculator'),
} as const

export const JOBS: Job[] = [
  { id: 'night-cleaning', title: 'Night Cleaning Shift', salary: 340, reputationRequired: 0, certifications: [], description: 'Low pay, rough hours, and just enough money to stay in motion.', ...JOB_IMAGES.cleaning },
  { id: 'odd-jobs', title: 'Odd Jobs Circuit', salary: 520, reputationRequired: 0, certifications: [], description: 'Temp shifts, cleaning gigs, and moving boxes just to stay afloat.', ...JOB_IMAGES.labor },
  { id: 'cafe', title: 'Cafe Shift Lead', salary: 760, reputationRequired: 2, certifications: [], description: 'Early mornings, steady tips, and a little more structure.', ...JOB_IMAGES.cafe },
  { id: 'warehouse', title: 'Warehouse Picker', salary: 920, reputationRequired: 3, certifications: [], description: 'Long hours and sore knees, but reliable weekly flow once you lock it in.', ...image('https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1200&q=80', 'Warehouse aisle with shelves and logistics equipment') },
  { id: 'hotel-front-desk', title: 'Hotel Front Desk', salary: 1080, reputationRequired: 3, certifications: [], description: 'Shift work with cleaner surroundings, tougher guests, and a better floor than raw labor.', ...JOB_IMAGES.hospitality },
  { id: 'clinic-reception', title: 'Clinic Reception', salary: 1180, reputationRequired: 4, certifications: [], description: 'Calmer surroundings, steady admin work, and a good bridge out of pure manual labor.', ...image('https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80', 'Reception desk in a modern clinic lobby') },
  { id: 'dispatcher', title: 'Local Dispatch Coordinator', salary: 1260, reputationRequired: 4, certifications: [], description: 'Phones, route changes, and constant problem-solving for a steadier mid-tier paycheck.', ...JOB_IMAGES.logistics },
  { id: 'sales', title: 'Sales Assistant', salary: 1400, reputationRequired: 5, certifications: ['sales-course'], description: 'Commission upside if you can keep a smile on hard days.', ...JOB_IMAGES.sales },
  { id: 'accounts-clerk', title: 'Accounts Clerk', salary: 1480, reputationRequired: 5, certifications: ['finance-cert'], description: 'Spreadsheets, invoicing, and steady office work that can turn into a real finance lane later.', ...JOB_IMAGES.office },
  { id: 'leasing-coordinator', title: 'Leasing Coordinator', salary: 1650, reputationRequired: 6, certifications: ['sales-course'], description: 'Closer to the property game: tours, follow-ups, and a cleaner line into real-estate work.', ...JOB_IMAGES.property },
  { id: 'operations-assistant', title: 'Operations Assistant', salary: 1780, reputationRequired: 6, certifications: ['coding-bootcamp'], description: 'Process cleanup, reporting, and enough system exposure to move out of pure hustle mode.', ...JOB_IMAGES.office },
  { id: 'analyst', title: 'Junior Market Analyst', salary: 1900, reputationRequired: 7, certifications: ['finance-cert'], description: 'You finally get paid to read charts instead of just staring at them.', ...JOB_IMAGES.analyst },
  { id: 'manager', title: 'Property Manager', salary: 2700, reputationRequired: 10, certifications: ['landlord-license'], description: 'Leasing, maintenance calls, and useful landlord contacts.', ...JOB_IMAGES.property },
  { id: 'operator', title: 'Startup Operations Lead', salary: 3500, reputationRequired: 14, certifications: ['coding-bootcamp'], description: 'Fast money, fast chaos, and finally enough cash to choose scale instead of survival.', ...JOB_IMAGES.startup },
]

export const SIDE_JOBS: SideJob[] = [
  {
    id: 'delivery-route',
    title: 'Scheduled Delivery Route',
    category: 'shift',
    schedule: 'evening',
    commitment: 'medium',
    weeklyPay: 85,
    reputationRequired: 0,
    certifications: [],
    description: 'Reliable dinner-block delivery work that pays every week but burns energy if you stack it on top of everything else.',
    weeklyStress: 5,
    weeklyEnergy: 9,
    reputationGain: 1,
    contactId: 'contractor',
    ...SKILL_IMAGES.mobility,
  },
  {
    id: 'campus-desk',
    title: 'Campus Desk Shift',
    category: 'shift',
    schedule: 'daytime',
    commitment: 'light',
    weeklyPay: 55,
    reputationRequired: 1,
    certifications: [],
    description: 'Low-drama front-desk work that pays modestly and fits better around studying than heavier labor does.',
    weeklyStress: 1,
    weeklyEnergy: 3,
    reputationGain: 1,
    knowledgeGain: 1,
    contactId: 'recruiter',
    ...SKILL_IMAGES.sales,
  },
  {
    id: 'morning-bakery',
    title: 'Morning Bakery Prep',
    category: 'shift',
    schedule: 'daytime',
    commitment: 'medium',
    weeklyPay: 78,
    reputationRequired: 0,
    certifications: [],
    description: 'Early prep shifts that are repetitive but dependable if you can live with the hours.',
    weeklyStress: 2,
    weeklyEnergy: 6,
    reputationGain: 1,
    ...JOB_IMAGES.cafe,
  },
  {
    id: 'commission-nights',
    title: 'Commission Nights',
    category: 'shift',
    schedule: 'evening',
    commitment: 'medium',
    weeklyPay: 115,
    reputationRequired: 3,
    certifications: ['sales-course'],
    description: 'Evening sales work with better upside if you can keep your energy and your pitch together.',
    weeklyStress: 4,
    weeklyEnergy: 7,
    reputationGain: 2,
    contactId: 'recruiter',
    ...JOB_IMAGES.sales,
  },
  {
    id: 'pet-sitting',
    title: 'Pet Sitting Loop',
    category: 'freelance',
    schedule: 'flex',
    commitment: 'light',
    weeklyPay: 68,
    reputationRequired: 1,
    certifications: [],
    description: 'Reliable neighborhood pet care that pays modestly and is easier on the body than heavier side work.',
    weeklyStress: 1,
    weeklyEnergy: 2,
    reputationGain: 1,
    contactId: 'recruiter',
    ...image('https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1200&q=80', 'Dog walker with a friendly dog in a city park'),
  },
  {
    id: 'night-auditor',
    title: 'Night Auditor Shift',
    category: 'shift',
    schedule: 'evening',
    commitment: 'light',
    weeklyPay: 92,
    reputationRequired: 2,
    certifications: [],
    description: 'Calmer desk work on slow hotel nights. Better than cleaning, but it still scrambles your sleep if you stack it badly.',
    weeklyStress: 2,
    weeklyEnergy: 5,
    reputationGain: 1,
    contactId: 'banker',
    ...JOB_IMAGES.hospitality,
  },
  {
    id: 'handyman-helper',
    title: 'Handyman Helper',
    category: 'shift',
    schedule: 'weekend',
    commitment: 'medium',
    weeklyPay: 105,
    reputationRequired: 4,
    certifications: ['landlord-license'],
    description: 'Small repair and turnover help that feeds directly into the property path and contractor relationships.',
    weeklyStress: 3,
    weeklyEnergy: 6,
    reputationGain: 1,
    contactId: 'contractor',
    ...SKILL_IMAGES.tools,
  },
  {
    id: 'leasing-runner',
    title: 'Leasing Runner',
    category: 'shift',
    schedule: 'weekend',
    commitment: 'light',
    weeklyPay: 88,
    reputationRequired: 3,
    certifications: ['sales-course'],
    description: 'Show units, run keys, and keep open-house weekends moving for property teams.',
    weeklyStress: 2,
    weeklyEnergy: 4,
    reputationGain: 2,
    contactId: 'broker',
    ...JOB_IMAGES.property,
  },
  {
    id: 'phone-support',
    title: 'Phone Support Queue',
    category: 'shift',
    schedule: 'evening',
    commitment: 'light',
    weeklyPay: 84,
    reputationRequired: 2,
    certifications: [],
    description: 'Low-pay support work, but it is clean, remote-friendly, and easier to pair with study than a physical shift.',
    weeklyStress: 3,
    weeklyEnergy: 3,
    reputationGain: 1,
    knowledgeGain: 1,
    bankAccountRequired: true,
    ...JOB_IMAGES.office,
  },
  {
    id: 'market-intern',
    title: 'Market Desk Internship',
    category: 'internship',
    schedule: 'daytime',
    commitment: 'light',
    weeklyPay: 75,
    reputationRequired: 5,
    certifications: ['finance-cert'],
    description: 'Bad pay, useful signal. It sharpens knowledge, grows banker trust, and improves the finance path later.',
    weeklyStress: 2,
    weeklyEnergy: 4,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'banker',
    bankAccountRequired: true,
    ...image('https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&w=1200&q=80', 'Financial internship style desk with charts and laptop'),
  },
  {
    id: 'remote-qa',
    title: 'Remote QA Sweep',
    category: 'freelance',
    schedule: 'flex',
    commitment: 'light',
    weeklyPay: 102,
    reputationRequired: 5,
    certifications: ['coding-bootcamp'],
    description: 'Bug sweeps, regression passes, and cleanup tickets that fit around the rest of the week better than full client work.',
    weeklyStress: 2,
    weeklyEnergy: 4,
    reputationGain: 1,
    knowledgeGain: 1,
    contactId: 'recruiter',
    bankAccountRequired: true,
    ...SKILL_IMAGES.coding,
  },
  {
    id: 'book-cart-restock',
    title: 'Book Cart Restock',
    category: 'shift',
    schedule: 'weekend',
    commitment: 'light',
    weeklyPay: 72,
    reputationRequired: 1,
    certifications: [],
    description: 'Quiet weekend stock work in a campus bookstore. Not exciting, but steady and low-drama.',
    weeklyStress: 1,
    weeklyEnergy: 3,
    reputationGain: 1,
    knowledgeGain: 1,
    contactId: 'recruiter',
    ...image('https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80', 'Bookstore shelves with a cart being stocked'),
  },
  {
    id: 'freelance-retainer',
    title: 'Freelance Retainer',
    category: 'freelance',
    schedule: 'flex',
    commitment: 'medium',
    weeklyPay: 150,
    reputationRequired: 7,
    certifications: ['coding-bootcamp'],
    description: 'Small weekly client maintenance work that compounds if you can keep it consistent beside everything else.',
    weeklyStress: 3,
    weeklyEnergy: 6,
    reputationGain: 1,
    contactId: 'recruiter',
    ...SKILL_IMAGES.coding,
  },
  {
    id: 'open-house-host',
    title: 'Open House Host',
    category: 'freelance',
    schedule: 'weekend',
    commitment: 'medium',
    weeklyPay: 134,
    reputationRequired: 5,
    certifications: ['landlord-license'],
    description: 'Temporary showing coverage for brokers and landlords. Good signal if you want more property exposure without buying yet.',
    weeklyStress: 3,
    weeklyEnergy: 5,
    reputationGain: 2,
    contactId: 'broker',
    ...JOB_IMAGES.property,
  },
  {
    id: 'festival-crew',
    title: 'Festival Crew',
    category: 'seasonal',
    schedule: 'weekend',
    commitment: 'heavy',
    weeklyPay: 170,
    reputationRequired: 1,
    certifications: [],
    description: 'Busy event-season work with sharp weekly cash, long hours, and a clear seasonal window.',
    weeklyStress: 6,
    weeklyEnergy: 10,
    reputationGain: 1,
    contactId: 'broker',
    seasonMonths: [6, 7, 8],
    ...image('https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80', 'Festival crew working under event lights'),
  },
  {
    id: 'holiday-retail',
    title: 'Holiday Retail Push',
    category: 'seasonal',
    schedule: 'weekend',
    commitment: 'heavy',
    weeklyPay: 155,
    reputationRequired: 2,
    certifications: ['sales-course'],
    description: 'Holiday selling season pays well for a few months if you can handle the pace.',
    weeklyStress: 5,
    weeklyEnergy: 9,
    reputationGain: 2,
    contactId: 'recruiter',
    seasonMonths: [11, 12],
    ...image('https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80', 'Retail worker organizing holiday clothing displays'),
  },
  {
    id: 'startup-intern',
    title: 'Startup Ops Internship',
    category: 'internship',
    schedule: 'daytime',
    commitment: 'medium',
    weeklyPay: 95,
    reputationRequired: 6,
    certifications: ['coding-bootcamp'],
    description: 'Messy but valuable internship exposure that trades cash for skill, access, and startup credibility.',
    weeklyStress: 3,
    weeklyEnergy: 5,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'recruiter',
    bankAccountRequired: true,
    ...image('https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80', 'Startup internship style team discussion in a small office'),
  },
  {
    id: 'tax-season-clerk',
    title: 'Tax Season Clerk',
    category: 'seasonal',
    schedule: 'daytime',
    commitment: 'medium',
    weeklyPay: 128,
    reputationRequired: 4,
    certifications: ['finance-cert'],
    description: 'A temporary documentation grind that pays decently and strengthens the finance lane during filing season.',
    weeklyStress: 4,
    weeklyEnergy: 5,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'banker',
    seasonMonths: [2, 3, 4],
    bankAccountRequired: true,
    ...JOB_IMAGES.office,
  },
]

export const GIGS: Gig[] = [
  { id: 'flyers', title: 'Street Flyer Handout', payout: 45, reputationRequired: 0, certifications: [], description: 'Hours on your feet pushing leaflets for barely enough cash to matter.', ...image('https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80', 'Promotional worker handing out flyers on a city street') },
  { id: 'delivery', title: 'Food Delivery Rush', payout: 95, reputationRequired: 0, certifications: [], description: 'A brutal extra push for quick weekly cash.', ...SKILL_IMAGES.mobility },
  { id: 'move-out-clean', title: 'Move-Out Clean', payout: 102, reputationRequired: 1, certifications: [], description: 'Hard, unglamorous reset work for somebody else’s deadline.', ...JOB_IMAGES.cleaning },
  { id: 'promo-crew', title: 'Promo Crew Setup', payout: 72, reputationRequired: 1, certifications: [], description: 'Unload stands, hang banners, and break everything back down before the client notices the chaos.', ...image('https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80', 'Event crew setting up a branded activation space') },
  { id: 'inventory-count', title: 'Inventory Count Night', payout: 88, reputationRequired: 1, certifications: [], description: 'Tedious overnight counting work, but it pays a little better than the true bottom-tier hustles.', ...image('https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80', 'Retail inventory worker scanning shelves in a store') },
  { id: 'data-entry-blitz', title: 'Data Entry Blitz', payout: 118, reputationRequired: 2, certifications: [], description: 'A boring admin sprint with a firm deadline and a decent check if you can stay focused.', ...JOB_IMAGES.office },
  { id: 'market-stall', title: 'Weekend Market Stall', payout: 165, reputationRequired: 3, certifications: ['sales-course'], description: 'Move product, haggle hard, and make a decent one-off side margin.', ...image('https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1200&q=80', 'Seller working at an outdoor market stall') },
  { id: 'bike-courier-loop', title: 'Bike Courier Loop', payout: 132, reputationRequired: 2, certifications: [], description: 'Faster parcel runs around town. It is better money if your transport can keep up.', ...SKILL_IMAGES.mobility },
  { id: 'showing-assist', title: 'Property Showing Assist', payout: 132, reputationRequired: 4, certifications: ['sales-course'], description: 'Help stage, open, and reset fast apartment tours for a busy broker schedule.', ...JOB_IMAGES.property },
  { id: 'tutoring', title: 'Exam Prep Tutoring', payout: 185, reputationRequired: 5, certifications: ['finance-cert'], description: 'Solid pay for sharp prep sessions and patient explanations.', ...image('https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80', 'Tutor helping a student with notes and a laptop') },
  { id: 'bookkeeping-sprint', title: 'Bookkeeping Cleanup Sprint', payout: 208, reputationRequired: 6, certifications: ['finance-cert'], description: 'Messy small-business books, hard deadline, decent check if you can tame the spreadsheet pile.', ...JOB_IMAGES.office },
  { id: 'freelance', title: 'Freelance Web Fix', payout: 235, reputationRequired: 7, certifications: ['coding-bootcamp'], description: 'Patch a landing page, send an invoice, repeat when needed.', ...SKILL_IMAGES.coding },
  { id: 'landing-page-build', title: 'Landing Page Build', payout: 285, reputationRequired: 8, certifications: ['coding-bootcamp'], description: 'A cleaner freelance build than emergency fixes, but only if your coding lane is already credible.', ...image('https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80', 'Developer building a website on dual monitors') },
  { id: 'repair-callout', title: 'Property Repair Callout', payout: 145, reputationRequired: 4, certifications: ['landlord-license'], description: 'Handle snag lists and keep units market-ready.', needsProperty: true, ...SKILL_IMAGES.tools },
  { id: 'turnover-reset', title: 'Turnover Reset', payout: 198, reputationRequired: 6, certifications: ['landlord-license'], description: 'A fast unit turnover push: cleanup, patching, and making a rental feel marketable again.', needsProperty: true, ...image('https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', 'Apartment interior being reset and cleaned for the next tenant') },
]

export const COURSES: Course[] = [
  { id: 'sales-course', title: 'Sales Course', cost: 420, reputationRequired: 2, description: 'A cleaner route into better customer-facing work and sales-heavy side jobs.', ...SKILL_IMAGES.sales },
  { id: 'finance-cert', title: 'Finance Certificate', cost: 880, reputationRequired: 4, description: 'Builds a real finance lane instead of leaving you stuck reading markets from the outside.', ...SKILL_IMAGES.finance },
  { id: 'landlord-license', title: 'Landlord License', cost: 640, reputationRequired: 4, description: 'Opens property gigs, field work, and the more serious real-estate jobs.', ...SKILL_IMAGES.property },
  { id: 'coding-bootcamp', title: 'Coding Bootcamp', cost: 1220, reputationRequired: 6, description: 'The biggest jump in earning power if you can survive the study cost and time hit.', ...SKILL_IMAGES.coding },
]

export const UPGRADES: Upgrade[] = [
  { id: 'scooter', title: 'Secondhand Scooter', cost: 650, description: 'Delivery work pays more because you can take more orders.', ...SKILL_IMAGES.mobility },
  { id: 'toolkit', title: 'Tool Kit', cost: 480, description: 'Renovations cost less and repair gigs pay a little extra.', ...SKILL_IMAGES.tools },
  { id: 'tenant-crm', title: 'Tenant CRM', cost: 900, description: 'Boost rent collection and lower vacancy risk.', ...SKILL_IMAGES.crm },
  { id: 'broker-terminal', title: 'Broker Terminal', cost: 1200, description: 'Cuts trading fees and improves dividend income.', ...SKILL_IMAGES.finance },
  { id: 'emergency-fund', title: 'Emergency Reserve System', cost: 850, description: 'Tighter budgeting trims your monthly living costs.', ...SKILL_IMAGES.emergency },
]

export const JOB_MAP = Object.fromEntries(JOBS.map((item) => [item.id, item])) as Record<string, Job>
export const SIDE_JOB_MAP = Object.fromEntries(SIDE_JOBS.map((item) => [item.id, item])) as Record<string, SideJob>
export const GIG_MAP = Object.fromEntries(GIGS.map((item) => [item.id, item])) as Record<string, Gig>
export const COURSE_MAP = Object.fromEntries(COURSES.map((item) => [item.id, item])) as Record<string, Course>
export const UPGRADE_MAP = Object.fromEntries(UPGRADES.map((item) => [item.id, item])) as Record<string, Upgrade>
