import type { CareerFieldDefinition, Course, Gig, Job, SideJob, Upgrade } from '../../game/core/types'

const image = (imageUrl: string, imageAlt: string) => ({ imageUrl, imageAlt })

const FIELD_IMAGES = {
  operations: image('https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1200&q=80', 'Warehouse aisle with logistics equipment and pallets'),
  finance: image('https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80', 'Finance desk with charts, calculator, and invoices'),
  property: image('https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80', 'Apartment building exterior with management signage'),
  sales: image('https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80', 'Retail worker helping a customer in a modern store'),
  tech: image('https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80', 'Developer workstation with code on screen'),
  health: image('https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80', 'Clinic front desk with patient sign-in area'),
  office: image('https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80', 'Office desk with laptop and reports'),
  tools: image('https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80', 'Hand tools laid out on a workbench'),
  mobility: image('https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=80', 'Scooter parked on an urban street'),
  hospitality: image('https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80', 'Hotel front desk worker helping a guest'),
  market: image('https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80', 'Laptop with financial dashboard and spreadsheet'),
  startup: image('https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80', 'Startup team collaborating around a table'),
} as const

export const CAREER_FIELDS: CareerFieldDefinition[] = [
  {
    id: 'operations-logistics',
    label: 'Operations & Logistics',
    description: 'Move from rough shift work into dispatch, systems, and the people who keep physical businesses moving.',
    accent: '#0f9ea8',
    preferredCertificationIds: ['operations-systems-cert', 'route-planning-cert'],
    preferredProgramIds: ['logistics-diploma', 'operations-bachelor', 'operations-masters'],
    ladderLabels: {
      entry: 'Entry shift',
      skilled: 'Reliable operator',
      specialist: 'Coordinator',
      manager: 'Fulfillment lead',
      executive: 'Network-scale manager',
    },
    ...FIELD_IMAGES.operations,
  },
  {
    id: 'finance-accounting',
    label: 'Finance & Accounting',
    description: 'Climb from cash-office work into bookkeeping, analysis, and higher-trust finance roles.',
    accent: '#2d8be6',
    preferredCertificationIds: ['finance-cert', 'bookkeeping-cert', 'payroll-cert'],
    preferredProgramIds: ['finance-night-school', 'accounting-diploma', 'finance-bachelor', 'finance-masters'],
    ladderLabels: {
      entry: 'Back office',
      skilled: 'Clerk',
      specialist: 'Bookkeeping',
      manager: 'Associate',
      executive: 'Controller track',
    },
    ...FIELD_IMAGES.finance,
  },
  {
    id: 'property-real-estate',
    label: 'Property & Real Estate',
    description: 'Start around tours and maintenance, then move into leasing, asset coordination, and portfolio operations.',
    accent: '#7f6ef2',
    preferredCertificationIds: ['landlord-license', 'property-maintenance-cert'],
    preferredProgramIds: ['property-operations', 'real-estate-diploma', 'property-bachelor', 'property-masters'],
    ladderLabels: {
      entry: 'Showing and site work',
      skilled: 'Leasing lane',
      specialist: 'Operations',
      manager: 'Property lead',
      executive: 'Portfolio operator',
    },
    ...FIELD_IMAGES.property,
  },
  {
    id: 'sales-marketing',
    label: 'Sales & Marketing',
    description: 'Build from floor work and promotions into account handling, campaigns, and higher-variance growth roles.',
    accent: '#1ab087',
    preferredCertificationIds: ['sales-course', 'crm-analytics-cert'],
    preferredProgramIds: ['sales-diploma', 'marketing-bachelor'],
    ladderLabels: {
      entry: 'Frontline selling',
      skilled: 'Closer',
      specialist: 'Account and campaign',
      manager: 'Growth lead',
      executive: 'Regional lead',
    },
    ...FIELD_IMAGES.sales,
  },
  {
    id: 'technology-product',
    label: 'Technology & Product',
    description: 'Use QA, support, and systems work to climb into product ops, implementation, and software-heavy roles.',
    accent: '#4f79ff',
    preferredCertificationIds: ['coding-bootcamp', 'qa-certificate', 'support-systems-cert'],
    preferredProgramIds: ['software-apprenticeship', 'software-bachelor', 'product-masters'],
    ladderLabels: {
      entry: 'Support desk',
      skilled: 'QA and implementation',
      specialist: 'Ops analyst',
      manager: 'Developer and product',
      executive: 'Startup operator',
    },
    ...FIELD_IMAGES.tech,
  },
  {
    id: 'healthcare-administration',
    label: 'Healthcare & Administration',
    description: 'Go from reception and records into billing, compliance, office management, and healthcare operations.',
    accent: '#dd7a44',
    preferredCertificationIds: ['healthcare-admin-cert', 'medical-billing-cert', 'compliance-admin-cert'],
    preferredProgramIds: ['healthcare-admin-diploma', 'healthcare-bachelor', 'healthcare-masters'],
    ladderLabels: {
      entry: 'Front desk',
      skilled: 'Records and billing',
      specialist: 'Clinic admin',
      manager: 'Office lead',
      executive: 'Compliance and operations',
    },
    ...FIELD_IMAGES.health,
  },
]

export const CAREER_FIELD_MAP = Object.fromEntries(CAREER_FIELDS.map((field) => [field.id, field])) as Record<(typeof CAREER_FIELDS)[number]['id'], CareerFieldDefinition>

export const LADDER_TIER_LABELS = {
  entry: 'Entry',
  skilled: 'Skilled',
  specialist: 'Specialist',
  manager: 'Manager',
  executive: 'Executive',
} as const

function job(jobData: Job): Job {
  return jobData
}

function sideJob(sideJobData: SideJob): SideJob {
  return sideJobData
}

function gig(gigData: Gig): Gig {
  return gigData
}

function course(courseData: Course): Course {
  return courseData
}

export const JOBS: Job[] = [
  job({
    id: 'night-cleaning',
    title: 'Night Cleaning Shift',
    salary: 340,
    reputationRequired: 0,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'entry',
    trackTags: ['labor', 'graveyard', 'facility'],
    nextJobIds: ['odd-jobs', 'stockroom-clerk'],
    recommendedProgramIds: ['community-college-basics', 'logistics-diploma'],
    description: 'Rough hours and thin pay, but it is honest facility work that can still get you into steadier operations lanes later.',
    ...FIELD_IMAGES.operations,
  }),
  job({
    id: 'odd-jobs',
    title: 'Odd Jobs Circuit',
    salary: 520,
    reputationRequired: 0,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'entry',
    trackTags: ['temp', 'labor', 'survival'],
    nextJobIds: ['stockroom-clerk', 'warehouse'],
    recommendedProgramIds: ['community-college-basics', 'logistics-diploma'],
    description: 'Temp shifts, moving days, cleanup blocks, and enough hustle to stay above zero while you build a cleaner lane.',
    ...FIELD_IMAGES.operations,
  }),
  job({
    id: 'stockroom-clerk',
    title: 'Stockroom Clerk',
    salary: 660,
    reputationRequired: 1,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'entry',
    trackTags: ['inventory', 'warehouse', 'back-room'],
    nextJobIds: ['warehouse', 'delivery-desk-assistant'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'Inventory counts, pallets, and receiving logs. It is still physical, but it starts to look like a real ladder.',
    ...FIELD_IMAGES.operations,
  }),
  job({
    id: 'warehouse',
    title: 'Warehouse Picker',
    salary: 920,
    reputationRequired: 3,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'skilled',
    trackTags: ['warehouse', 'reliable', 'fulfillment'],
    nextJobIds: ['delivery-desk-assistant', 'dispatcher'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'Long shifts and sore knees, but reliable throughput work with a clean line into dispatch or lead-floor roles.',
    ...FIELD_IMAGES.operations,
  }),
  job({
    id: 'delivery-desk-assistant',
    title: 'Delivery Desk Assistant',
    salary: 1080,
    reputationRequired: 4,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'skilled',
    trackTags: ['routing', 'desk', 'last-mile'],
    nextJobIds: ['dispatcher', 'route-supervisor'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'Manifest updates, route handoffs, and proof-of-delivery cleanup for a steadier logistics desk role.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'dispatcher',
    title: 'Route Dispatcher',
    salary: 1240,
    reputationRequired: 4,
    certifications: ['route-planning-cert'],
    careerField: 'operations-logistics',
    ladderTier: 'specialist',
    trackTags: ['dispatch', 'routing', 'coordination'],
    nextJobIds: ['local-dispatch-coordinator', 'route-supervisor'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'Phones, route changes, missed windows, and enough problem-solving to feel like a real operations lane.',
    ...FIELD_IMAGES.operations,
  }),
  job({
    id: 'local-dispatch-coordinator',
    title: 'Local Dispatch Coordinator',
    salary: 1440,
    reputationRequired: 5,
    certifications: ['route-planning-cert'],
    careerField: 'operations-logistics',
    ladderTier: 'specialist',
    trackTags: ['coordination', 'routing', 'local-ops'],
    nextJobIds: ['route-supervisor', 'fulfillment-analyst'],
    recommendedProgramIds: ['logistics-diploma', 'operations-bachelor'],
    description: 'You own the route board, solve mid-day messes, and start getting trusted with the ugly stuff that actually matters.',
    ...FIELD_IMAGES.operations,
  }),
  job({
    id: 'route-supervisor',
    title: 'Route Supervisor',
    salary: 1760,
    reputationRequired: 7,
    certifications: ['operations-systems-cert', 'route-planning-cert'],
    careerField: 'operations-logistics',
    ladderTier: 'manager',
    trackTags: ['supervision', 'fleet', 'shift-lead'],
    nextJobIds: ['fulfillment-analyst', 'logistics-manager'],
    recommendedProgramIds: ['logistics-diploma', 'operations-bachelor'],
    description: 'Shift planning, driver issues, and enough oversight to start separating yourself from the floor.',
    ...FIELD_IMAGES.operations,
  }),
  job({
    id: 'fulfillment-analyst',
    title: 'Fulfillment Analyst',
    salary: 2140,
    reputationRequired: 9,
    certifications: ['operations-systems-cert'],
    programRequirements: ['logistics-diploma'],
    careerField: 'operations-logistics',
    ladderTier: 'manager',
    trackTags: ['analytics', 'fulfillment', 'systems'],
    nextJobIds: ['logistics-manager'],
    recommendedProgramIds: ['operations-bachelor', 'operations-masters'],
    description: 'Forecasts, labor planning, and warehouse throughput work that finally moves you from reactive to analytical operations.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'logistics-manager',
    title: 'Logistics Manager',
    salary: 2920,
    reputationRequired: 12,
    certifications: ['operations-systems-cert'],
    programRequirements: ['operations-bachelor'],
    careerField: 'operations-logistics',
    ladderTier: 'executive',
    trackTags: ['management', 'network', 'throughput'],
    nextJobIds: [],
    recommendedProgramIds: ['operations-masters'],
    description: 'You are managing headcount, route health, vendor friction, and enough system complexity to feel like a real upper track.',
    ...FIELD_IMAGES.operations,
  }),

  job({
    id: 'cash-office-assistant',
    title: 'Cash Office Assistant',
    salary: 430,
    reputationRequired: 0,
    certifications: [],
    careerField: 'finance-accounting',
    ladderTier: 'entry',
    trackTags: ['cash-handling', 'retail-finance', 'back-office'],
    nextJobIds: ['billing-clerk', 'accounts-clerk'],
    recommendedProgramIds: ['community-college-basics', 'finance-night-school'],
    description: 'Count tills, close small books, and do the quiet money work nobody notices until it goes wrong.',
    ...FIELD_IMAGES.finance,
  }),
  job({
    id: 'billing-clerk',
    title: 'Billing Clerk',
    salary: 620,
    reputationRequired: 1,
    certifications: [],
    careerField: 'finance-accounting',
    ladderTier: 'entry',
    trackTags: ['billing', 'invoices', 'clerical'],
    nextJobIds: ['accounts-clerk', 'ap-helper'],
    recommendedProgramIds: ['finance-night-school', 'accounting-diploma'],
    description: 'Invoices, due dates, and enough repetition to teach you whether you actually like finance work.',
    ...FIELD_IMAGES.finance,
  }),
  job({
    id: 'accounts-clerk',
    title: 'Accounts Clerk',
    salary: 860,
    reputationRequired: 3,
    certifications: ['finance-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'skilled',
    trackTags: ['accounts', 'office', 'finance'],
    nextJobIds: ['ap-helper', 'bookkeeper'],
    recommendedProgramIds: ['finance-night-school', 'accounting-diploma'],
    description: 'Reconciliations, invoices, and cleaner office work that can turn into real bookkeeping or payroll.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'ap-helper',
    title: 'AP Helper',
    salary: 1080,
    reputationRequired: 4,
    certifications: ['finance-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'skilled',
    trackTags: ['accounts-payable', 'invoices', 'vendors'],
    nextJobIds: ['bookkeeper', 'payroll-assistant'],
    recommendedProgramIds: ['accounting-diploma'],
    description: 'Vendor statements, payment runs, and practical accounting work with a stronger ladder than generic office admin.',
    ...FIELD_IMAGES.finance,
  }),
  job({
    id: 'bookkeeper',
    title: 'Bookkeeper',
    salary: 1360,
    reputationRequired: 5,
    certifications: ['bookkeeping-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'specialist',
    trackTags: ['bookkeeping', 'small-business', 'ledgers'],
    nextJobIds: ['payroll-assistant', 'finance-associate'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    description: 'You keep a real set of books straight. That finally reads like a finance identity instead of just clerical work.',
    ...FIELD_IMAGES.finance,
  }),
  job({
    id: 'payroll-assistant',
    title: 'Payroll Assistant',
    salary: 1560,
    reputationRequired: 6,
    certifications: ['bookkeeping-cert', 'payroll-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'specialist',
    trackTags: ['payroll', 'compliance', 'back-office'],
    nextJobIds: ['finance-associate', 'analyst'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    description: 'More trust, more deadlines, and fewer places to hide mistakes. It is a cleaner rung with real signal.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'finance-associate',
    title: 'Finance Associate',
    salary: 1980,
    reputationRequired: 8,
    certifications: ['finance-cert', 'bookkeeping-cert'],
    programRequirements: ['accounting-diploma'],
    careerField: 'finance-accounting',
    ladderTier: 'manager',
    trackTags: ['analysis', 'planning', 'associate'],
    nextJobIds: ['analyst', 'controller-track-analyst'],
    recommendedProgramIds: ['finance-bachelor', 'finance-masters'],
    description: 'You are finally in the kind of role that turns finance training into a long-run lane instead of a side credential.',
    ...FIELD_IMAGES.finance,
  }),
  job({
    id: 'analyst',
    title: 'Junior Market Analyst',
    salary: 2380,
    reputationRequired: 10,
    certifications: ['finance-cert'],
    programRequirements: ['finance-bachelor'],
    careerField: 'finance-accounting',
    ladderTier: 'manager',
    trackTags: ['analysis', 'markets', 'research'],
    nextJobIds: ['controller-track-analyst'],
    recommendedProgramIds: ['finance-masters'],
    description: 'You finally get paid to read numbers instead of just staring at them from the outside.',
    ...FIELD_IMAGES.market,
  }),
  job({
    id: 'controller-track-analyst',
    title: 'Controller-Track Analyst',
    salary: 3320,
    reputationRequired: 14,
    certifications: ['finance-cert', 'payroll-cert'],
    programRequirements: ['finance-masters'],
    careerField: 'finance-accounting',
    ladderTier: 'executive',
    trackTags: ['controller-track', 'leadership', 'finance'],
    nextJobIds: [],
    recommendedProgramIds: [],
    description: 'Forecasts, close cycles, audit prep, and the first real look at upper finance leadership work.',
    ...FIELD_IMAGES.finance,
  }),
  job({
    id: 'showing-runner',
    title: 'Showing Runner',
    salary: 420,
    reputationRequired: 0,
    certifications: [],
    careerField: 'property-real-estate',
    ladderTier: 'entry',
    trackTags: ['showings', 'keys', 'real-estate'],
    nextJobIds: ['maintenance-helper', 'hotel-front-desk'],
    recommendedProgramIds: ['property-operations', 'real-estate-diploma'],
    description: 'Keys, lockboxes, and rushing between units. It is low-status work, but it gets you into the property orbit.',
    ...FIELD_IMAGES.property,
  }),
  job({
    id: 'maintenance-helper',
    title: 'Maintenance Helper',
    salary: 620,
    reputationRequired: 1,
    certifications: [],
    careerField: 'property-real-estate',
    ladderTier: 'entry',
    trackTags: ['maintenance', 'repairs', 'turnovers'],
    nextJobIds: ['hotel-front-desk', 'leasing-coordinator'],
    recommendedProgramIds: ['property-operations', 'real-estate-diploma'],
    description: 'Snag lists, patch jobs, and turnover prep that feeds directly into building ops and contractor relationships.',
    ...FIELD_IMAGES.tools,
  }),
  job({
    id: 'hotel-front-desk',
    title: 'Front Desk Leasing Support',
    salary: 820,
    reputationRequired: 2,
    certifications: [],
    careerField: 'property-real-estate',
    ladderTier: 'skilled',
    trackTags: ['front-desk', 'leasing', 'tenant-facing'],
    nextJobIds: ['leasing-coordinator', 'tenant-services-assistant'],
    recommendedProgramIds: ['property-operations'],
    description: 'Guest and tenant-style service, scheduling, and follow-up that transitions surprisingly well into leasing support.',
    ...FIELD_IMAGES.hospitality,
  }),
  job({
    id: 'leasing-coordinator',
    title: 'Leasing Coordinator',
    salary: 1180,
    reputationRequired: 4,
    certifications: ['sales-course'],
    careerField: 'property-real-estate',
    ladderTier: 'skilled',
    trackTags: ['leasing', 'showings', 'follow-up'],
    nextJobIds: ['tenant-services-assistant', 'property-operations-assistant'],
    recommendedProgramIds: ['property-operations', 'real-estate-diploma'],
    description: 'Tours, callbacks, applications, and the first role that really feels like the property lane is opening.',
    ...FIELD_IMAGES.property,
  }),
  job({
    id: 'tenant-services-assistant',
    title: 'Tenant Services Assistant',
    salary: 1360,
    reputationRequired: 5,
    certifications: ['landlord-license'],
    careerField: 'property-real-estate',
    ladderTier: 'specialist',
    trackTags: ['tenant-services', 'admin', 'property'],
    nextJobIds: ['property-operations-assistant', 'assistant-property-manager'],
    recommendedProgramIds: ['real-estate-diploma'],
    description: 'Move-in issues, rent questions, maintenance handoffs, and all the practical work that keeps buildings occupied.',
    ...FIELD_IMAGES.property,
  }),
  job({
    id: 'property-operations-assistant',
    title: 'Property Operations Assistant',
    salary: 1580,
    reputationRequired: 6,
    certifications: ['landlord-license', 'property-maintenance-cert'],
    careerField: 'property-real-estate',
    ladderTier: 'specialist',
    trackTags: ['operations', 'maintenance', 'systems'],
    nextJobIds: ['assistant-property-manager', 'manager'],
    recommendedProgramIds: ['real-estate-diploma', 'property-bachelor'],
    description: 'Work orders, vendor coordination, occupancy reporting, and enough systems exposure to move beyond raw leasing.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'assistant-property-manager',
    title: 'Assistant Property Manager',
    salary: 1920,
    reputationRequired: 8,
    certifications: ['landlord-license'],
    programRequirements: ['real-estate-diploma'],
    careerField: 'property-real-estate',
    ladderTier: 'manager',
    trackTags: ['management', 'buildings', 'tenants'],
    nextJobIds: ['manager', 'asset-coordinator'],
    recommendedProgramIds: ['property-bachelor', 'property-masters'],
    description: 'You are now close enough to the numbers, tenants, and contractors that this starts to feel like a real property career.',
    ...FIELD_IMAGES.property,
  }),
  job({
    id: 'manager',
    title: 'Property Manager',
    salary: 2480,
    reputationRequired: 10,
    certifications: ['landlord-license', 'property-maintenance-cert'],
    programRequirements: ['property-bachelor'],
    careerField: 'property-real-estate',
    ladderTier: 'manager',
    trackTags: ['management', 'leasing', 'portfolio'],
    nextJobIds: ['asset-coordinator'],
    recommendedProgramIds: ['property-masters'],
    description: 'Leasing, maintenance calls, vendors, occupancy, and enough responsibility that the month starts to revolve around you.',
    ...FIELD_IMAGES.property,
  }),
  job({
    id: 'asset-coordinator',
    title: 'Asset Coordinator',
    salary: 3160,
    reputationRequired: 13,
    certifications: ['landlord-license'],
    programRequirements: ['property-masters'],
    careerField: 'property-real-estate',
    ladderTier: 'executive',
    trackTags: ['asset-management', 'portfolio', 'reporting'],
    nextJobIds: [],
    recommendedProgramIds: [],
    description: 'Portfolio reporting, capital plans, and the kind of cleaner property role that a formal credential stack finally unlocks.',
    ...FIELD_IMAGES.property,
  }),

  job({
    id: 'retail-floor',
    title: 'Retail Floor Associate',
    salary: 420,
    reputationRequired: 0,
    certifications: [],
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    trackTags: ['retail', 'floor', 'customer-facing'],
    nextJobIds: ['cafe', 'call-center-upsell'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Product questions, folding tables, and the first hint that people skills can compound into better work.',
    ...FIELD_IMAGES.sales,
  }),
  job({
    id: 'cafe',
    title: 'Cafe Shift Lead',
    salary: 760,
    reputationRequired: 2,
    certifications: [],
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    trackTags: ['service', 'tips', 'customer'],
    nextJobIds: ['call-center-upsell', 'sales'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Early mornings, steady tips, and enough customer pressure to train the basics of selling and keeping calm.',
    ...FIELD_IMAGES.sales,
  }),
  job({
    id: 'call-center-upsell',
    title: 'Call-Center Upsell Rep',
    salary: 940,
    reputationRequired: 3,
    certifications: ['sales-course'],
    careerField: 'sales-marketing',
    ladderTier: 'skilled',
    trackTags: ['phone-sales', 'upsell', 'volume'],
    nextJobIds: ['sales', 'promo-account-assistant'],
    recommendedProgramIds: ['sales-diploma', 'marketing-bachelor'],
    description: 'Scripted pressure, quotas, and the first role where pure selling ability can actually move your paycheck.',
    ...FIELD_IMAGES.sales,
  }),
  job({
    id: 'promo-account-assistant',
    title: 'Promo Account Assistant',
    salary: 1120,
    reputationRequired: 4,
    certifications: ['sales-course'],
    careerField: 'sales-marketing',
    ladderTier: 'skilled',
    trackTags: ['events', 'brand', 'coordination'],
    nextJobIds: ['sales', 'campaign-support'],
    recommendedProgramIds: ['sales-diploma', 'marketing-bachelor'],
    description: 'Brand activations, client notes, and enough campaign exposure to start separating sales from pure retail.',
    ...FIELD_IMAGES.sales,
  }),
  job({
    id: 'sales',
    title: 'Sales Assistant',
    salary: 1360,
    reputationRequired: 5,
    certifications: ['sales-course'],
    careerField: 'sales-marketing',
    ladderTier: 'specialist',
    trackTags: ['sales', 'commission', 'client'],
    nextJobIds: ['campaign-support', 'account-executive'],
    recommendedProgramIds: ['sales-diploma', 'marketing-bachelor'],
    description: 'Commission upside, client follow-up, and enough pressure that a strong week can actually change your month.',
    ...FIELD_IMAGES.sales,
  }),
  job({
    id: 'campaign-support',
    title: 'Campaign Support Coordinator',
    salary: 1580,
    reputationRequired: 6,
    certifications: ['sales-course', 'crm-analytics-cert'],
    careerField: 'sales-marketing',
    ladderTier: 'specialist',
    trackTags: ['campaigns', 'crm', 'support'],
    nextJobIds: ['account-executive', 'growth-specialist'],
    recommendedProgramIds: ['marketing-bachelor'],
    description: 'CRM cleanup, campaign reporting, and the first role where better marketing systems start to matter.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'account-executive',
    title: 'Account Executive',
    salary: 2060,
    reputationRequired: 8,
    certifications: ['sales-course', 'crm-analytics-cert'],
    programRequirements: ['sales-diploma'],
    careerField: 'sales-marketing',
    ladderTier: 'manager',
    trackTags: ['accounts', 'closing', 'pipeline'],
    nextJobIds: ['growth-specialist', 'regional-sales-lead'],
    recommendedProgramIds: ['marketing-bachelor'],
    description: 'You are running a live pipeline now, not just helping one. That makes selling feel a lot more like a career and a lot less like hustle.',
    ...FIELD_IMAGES.sales,
  }),
  job({
    id: 'growth-specialist',
    title: 'Growth Specialist',
    salary: 2660,
    reputationRequired: 10,
    certifications: ['crm-analytics-cert'],
    programRequirements: ['marketing-bachelor'],
    careerField: 'sales-marketing',
    ladderTier: 'manager',
    trackTags: ['growth', 'marketing', 'analytics'],
    nextJobIds: ['regional-sales-lead'],
    recommendedProgramIds: [],
    description: 'Campaign economics, channel testing, and the kind of cleaner upside that formal marketing training finally unlocks.',
    ...FIELD_IMAGES.market,
  }),
  job({
    id: 'regional-sales-lead',
    title: 'Regional Sales Lead',
    salary: 3360,
    reputationRequired: 13,
    certifications: ['sales-course', 'crm-analytics-cert'],
    programRequirements: ['marketing-bachelor'],
    careerField: 'sales-marketing',
    ladderTier: 'executive',
    trackTags: ['regional', 'management', 'accounts'],
    nextJobIds: [],
    recommendedProgramIds: [],
    description: 'Quota leadership, hiring input, and the bigger swings that come with managing revenue instead of just chasing it.',
    ...FIELD_IMAGES.sales,
  }),
  job({
    id: 'qa-sweep-runner',
    title: 'QA Sweep Runner',
    salary: 460,
    reputationRequired: 0,
    certifications: [],
    careerField: 'technology-product',
    ladderTier: 'entry',
    trackTags: ['qa', 'testing', 'tickets'],
    nextJobIds: ['support-desk-trainee', 'content-ops-assistant'],
    recommendedProgramIds: ['software-apprenticeship'],
    description: 'Low-status regression work, but it is often the first clean step out of pure manual labor and into software-adjacent work.',
    ...FIELD_IMAGES.tech,
  }),
  job({
    id: 'support-desk-trainee',
    title: 'Support Desk Trainee',
    salary: 660,
    reputationRequired: 1,
    certifications: [],
    careerField: 'technology-product',
    ladderTier: 'entry',
    trackTags: ['support', 'tickets', 'systems'],
    nextJobIds: ['content-ops-assistant', 'operations-assistant'],
    recommendedProgramIds: ['software-apprenticeship'],
    description: 'Simple tickets and calmer desk work that pays modestly but starts teaching systems thinking.',
    ...FIELD_IMAGES.tech,
  }),
  job({
    id: 'content-ops-assistant',
    title: 'Content Ops Assistant',
    salary: 860,
    reputationRequired: 3,
    certifications: ['support-systems-cert'],
    careerField: 'technology-product',
    ladderTier: 'skilled',
    trackTags: ['content-ops', 'cms', 'cleanup'],
    nextJobIds: ['operations-assistant', 'implementation-support'],
    recommendedProgramIds: ['software-apprenticeship'],
    description: 'CMS cleanup, uploads, and process tidying. It is not glamorous, but it puts you inside digital operations.',
    ...FIELD_IMAGES.tech,
  }),
  job({
    id: 'operations-assistant',
    title: 'Operations Assistant',
    salary: 1120,
    reputationRequired: 4,
    certifications: ['support-systems-cert'],
    careerField: 'technology-product',
    ladderTier: 'skilled',
    trackTags: ['ops', 'systems', 'implementation'],
    nextJobIds: ['implementation-support', 'product-ops-analyst'],
    recommendedProgramIds: ['software-apprenticeship', 'software-bachelor'],
    description: 'Process cleanup, reporting, and enough systems exposure to move out of pure hustle mode.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'implementation-support',
    title: 'Implementation Support',
    salary: 1380,
    reputationRequired: 5,
    certifications: ['support-systems-cert', 'qa-certificate'],
    careerField: 'technology-product',
    ladderTier: 'specialist',
    trackTags: ['implementation', 'clients', 'systems'],
    nextJobIds: ['product-ops-analyst', 'junior-developer'],
    recommendedProgramIds: ['software-apprenticeship', 'software-bachelor'],
    description: 'Client setups, product rollouts, and the first time product work starts to feel like a real lane.',
    ...FIELD_IMAGES.tech,
  }),
  job({
    id: 'product-ops-analyst',
    title: 'Product Ops Analyst',
    salary: 1760,
    reputationRequired: 7,
    certifications: ['support-systems-cert', 'qa-certificate'],
    programRequirements: ['software-apprenticeship'],
    careerField: 'technology-product',
    ladderTier: 'specialist',
    trackTags: ['product-ops', 'analytics', 'systems'],
    nextJobIds: ['junior-developer', 'operator'],
    recommendedProgramIds: ['software-bachelor', 'product-masters'],
    description: 'Instrumentation, process fixes, and cross-team support that feels much closer to a real tech career than random gig coding.',
    ...FIELD_IMAGES.tech,
  }),
  job({
    id: 'junior-developer',
    title: 'Junior Developer',
    salary: 2380,
    reputationRequired: 9,
    certifications: ['coding-bootcamp'],
    programRequirements: ['software-bachelor'],
    careerField: 'technology-product',
    ladderTier: 'manager',
    trackTags: ['development', 'software', 'product'],
    nextJobIds: ['operator'],
    recommendedProgramIds: ['product-masters'],
    description: 'You are shipping real code now, not just cleaning tickets. The lane is finally paying back the study pain.',
    ...FIELD_IMAGES.tech,
  }),
  job({
    id: 'operator',
    title: 'Startup Operations Lead',
    salary: 3560,
    reputationRequired: 13,
    certifications: ['coding-bootcamp', 'support-systems-cert'],
    programRequirements: ['product-masters'],
    careerField: 'technology-product',
    ladderTier: 'executive',
    trackTags: ['startup', 'ops', 'leadership'],
    nextJobIds: [],
    recommendedProgramIds: [],
    description: 'Fast money, fast chaos, and the first upper-lane job that turns your product and systems stack into serious leverage.',
    ...FIELD_IMAGES.startup,
  }),

  job({
    id: 'records-runner',
    title: 'Records Runner',
    salary: 410,
    reputationRequired: 0,
    certifications: [],
    careerField: 'healthcare-administration',
    ladderTier: 'entry',
    trackTags: ['records', 'clinic', 'admin'],
    nextJobIds: ['patient-scheduler', 'clinic-reception'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Paper charts, filing, and enough quiet admin work to start proving you can handle a clinical office rhythm.',
    ...FIELD_IMAGES.health,
  }),
  job({
    id: 'patient-scheduler',
    title: 'Patient Scheduling Assistant',
    salary: 590,
    reputationRequired: 1,
    certifications: [],
    careerField: 'healthcare-administration',
    ladderTier: 'entry',
    trackTags: ['scheduling', 'patients', 'desk'],
    nextJobIds: ['clinic-reception', 'medical-records-clerk'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Phones, appointment windows, and enough patient traffic to start feeling the shape of healthcare admin work.',
    ...FIELD_IMAGES.health,
  }),
  job({
    id: 'clinic-reception',
    title: 'Clinic Reception',
    salary: 840,
    reputationRequired: 3,
    certifications: [],
    careerField: 'healthcare-administration',
    ladderTier: 'skilled',
    trackTags: ['reception', 'patients', 'front-desk'],
    nextJobIds: ['medical-records-clerk', 'medical-billing-specialist'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Calmer surroundings, steady admin work, and a good bridge into more structured healthcare-office roles.',
    ...FIELD_IMAGES.health,
  }),
  job({
    id: 'medical-records-clerk',
    title: 'Medical Records Clerk',
    salary: 1020,
    reputationRequired: 4,
    certifications: ['healthcare-admin-cert'],
    careerField: 'healthcare-administration',
    ladderTier: 'skilled',
    trackTags: ['records', 'compliance', 'clerical'],
    nextJobIds: ['medical-billing-specialist', 'practice-admin-support'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Files, releases, documentation quality, and the first role where process discipline starts to matter a lot.',
    ...FIELD_IMAGES.health,
  }),
  job({
    id: 'medical-billing-specialist',
    title: 'Medical Billing Specialist',
    salary: 1340,
    reputationRequired: 5,
    certifications: ['medical-billing-cert'],
    careerField: 'healthcare-administration',
    ladderTier: 'specialist',
    trackTags: ['billing', 'insurance', 'claims'],
    nextJobIds: ['practice-admin-support', 'office-manager-health'],
    recommendedProgramIds: ['healthcare-admin-diploma', 'healthcare-bachelor'],
    description: 'Claims, coding, and reimbursement work with cleaner upside than generic clinic reception ever gives you.',
    ...FIELD_IMAGES.health,
  }),
  job({
    id: 'practice-admin-support',
    title: 'Practice Admin Support',
    salary: 1580,
    reputationRequired: 6,
    certifications: ['healthcare-admin-cert'],
    programRequirements: ['healthcare-admin-diploma'],
    careerField: 'healthcare-administration',
    ladderTier: 'specialist',
    trackTags: ['practice-admin', 'operations', 'desk'],
    nextJobIds: ['office-manager-health', 'compliance-admin'],
    recommendedProgramIds: ['healthcare-bachelor', 'healthcare-masters'],
    description: 'You sit closer to staffing, scheduling, compliance, and the practical work of keeping a clinic running cleanly.',
    ...FIELD_IMAGES.office,
  }),
  job({
    id: 'office-manager-health',
    title: 'Healthcare Office Manager',
    salary: 2140,
    reputationRequired: 9,
    certifications: ['healthcare-admin-cert', 'medical-billing-cert'],
    programRequirements: ['healthcare-bachelor'],
    careerField: 'healthcare-administration',
    ladderTier: 'manager',
    trackTags: ['office-manager', 'staff', 'operations'],
    nextJobIds: ['compliance-admin', 'healthcare-operations-lead'],
    recommendedProgramIds: ['healthcare-masters'],
    description: 'Staff coverage, office metrics, patient flow, and the kind of broad admin responsibility that finally pays like a career.',
    ...FIELD_IMAGES.health,
  }),
  job({
    id: 'compliance-admin',
    title: 'Compliance Administrator',
    salary: 2840,
    reputationRequired: 12,
    certifications: ['compliance-admin-cert'],
    programRequirements: ['healthcare-masters'],
    careerField: 'healthcare-administration',
    ladderTier: 'executive',
    trackTags: ['compliance', 'healthcare', 'governance'],
    nextJobIds: ['healthcare-operations-lead'],
    recommendedProgramIds: [],
    description: 'Audits, policy cleanup, risk exposure, and enough formal responsibility that the degree path finally pays off.',
    ...FIELD_IMAGES.health,
  }),
  job({
    id: 'healthcare-operations-lead',
    title: 'Healthcare Operations Lead',
    salary: 3420,
    reputationRequired: 14,
    certifications: ['compliance-admin-cert', 'medical-billing-cert'],
    programRequirements: ['healthcare-masters'],
    careerField: 'healthcare-administration',
    ladderTier: 'executive',
    trackTags: ['operations', 'leadership', 'healthcare'],
    nextJobIds: [],
    recommendedProgramIds: [],
    description: 'Cross-site admin, staffing pressure, compliance risk, and the kind of upper healthcare admin work that is impossible to bluff your way into.',
    ...FIELD_IMAGES.health,
  }),
]

export const SIDE_JOBS: SideJob[] = [
  sideJob({
    id: 'delivery-route',
    title: 'Scheduled Delivery Route',
    category: 'shift',
    schedule: 'evening',
    commitment: 'medium',
    weeklyPay: 85,
    reputationRequired: 0,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'entry',
    trackTags: ['delivery', 'last-mile', 'bridge'],
    nextJobIds: ['dispatcher', 'local-dispatch-coordinator'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'Reliable dinner-block delivery work that pays every week and starts to build routing credibility.',
    weeklyStress: 5,
    weeklyEnergy: 9,
    reputationGain: 1,
    contactId: 'contractor',
    ...FIELD_IMAGES.mobility,
  }),
  sideJob({
    id: 'dispatch-overflow',
    title: 'Dispatch Overflow Desk',
    category: 'shift',
    schedule: 'evening',
    commitment: 'light',
    weeklyPay: 98,
    reputationRequired: 2,
    certifications: ['route-planning-cert'],
    careerField: 'operations-logistics',
    ladderTier: 'skilled',
    trackTags: ['dispatch', 'routing', 'bridge'],
    nextJobIds: ['dispatcher', 'local-dispatch-coordinator'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'Evening routing cleanup and missed-stop triage that directly feeds the dispatch ladder.',
    weeklyStress: 3,
    weeklyEnergy: 5,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'recruiter',
    bankAccountRequired: true,
    ...FIELD_IMAGES.operations,
  }),
  sideJob({
    id: 'inventory-receiver',
    title: 'Inventory Receiver',
    category: 'shift',
    schedule: 'weekend',
    commitment: 'medium',
    weeklyPay: 108,
    reputationRequired: 1,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'entry',
    trackTags: ['inventory', 'warehouse', 'bridge'],
    nextJobIds: ['stockroom-clerk', 'warehouse'],
    recommendedProgramIds: ['community-college-basics', 'logistics-diploma'],
    description: 'Weekend receiving work with cleaner paperwork than pure labor and a direct line into stockroom roles.',
    weeklyStress: 2,
    weeklyEnergy: 6,
    reputationGain: 1,
    ...FIELD_IMAGES.operations,
  }),
  sideJob({
    id: 'campus-desk',
    title: 'Campus Desk Shift',
    category: 'shift',
    schedule: 'daytime',
    commitment: 'light',
    weeklyPay: 55,
    reputationRequired: 1,
    certifications: [],
    careerField: 'healthcare-administration',
    ladderTier: 'entry',
    trackTags: ['desk', 'clerical', 'bridge'],
    nextJobIds: ['patient-scheduler', 'records-runner'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Low-drama desk work that pays modestly and teaches the basics of patient-facing admin discipline.',
    weeklyStress: 1,
    weeklyEnergy: 3,
    reputationGain: 1,
    knowledgeGain: 1,
    contactId: 'recruiter',
    ...FIELD_IMAGES.health,
  }),
  sideJob({
    id: 'records-filing-block',
    title: 'Records Filing Block',
    category: 'shift',
    schedule: 'weekend',
    commitment: 'light',
    weeklyPay: 74,
    reputationRequired: 1,
    certifications: [],
    careerField: 'healthcare-administration',
    ladderTier: 'entry',
    trackTags: ['records', 'admin', 'bridge'],
    nextJobIds: ['clinic-reception', 'medical-records-clerk'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Quiet filing work in a clinic back office. It is low-glamour, but it builds a usable admin signal.',
    weeklyStress: 1,
    weeklyEnergy: 2,
    reputationGain: 1,
    knowledgeGain: 1,
    contactId: 'recruiter',
    ...FIELD_IMAGES.health,
  }),
  sideJob({
    id: 'patient-callback-block',
    title: 'Patient Callback Block',
    category: 'shift',
    schedule: 'evening',
    commitment: 'light',
    weeklyPay: 86,
    reputationRequired: 3,
    certifications: ['healthcare-admin-cert'],
    careerField: 'healthcare-administration',
    ladderTier: 'skilled',
    trackTags: ['patients', 'phone', 'admin'],
    nextJobIds: ['clinic-reception', 'medical-billing-specialist'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Phone follow-up and schedule correction work that feeds directly into clinic admin credibility.',
    weeklyStress: 2,
    weeklyEnergy: 3,
    reputationGain: 2,
    contactId: 'recruiter',
    ...FIELD_IMAGES.health,
  }),
  sideJob({
    id: 'morning-bakery',
    title: 'Morning Bakery Prep',
    category: 'shift',
    schedule: 'daytime',
    commitment: 'medium',
    weeklyPay: 78,
    reputationRequired: 0,
    certifications: [],
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    trackTags: ['service', 'customer', 'bridge'],
    nextJobIds: ['cafe', 'retail-floor'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Early prep shifts that are repetitive but dependable and still build some service discipline.',
    weeklyStress: 2,
    weeklyEnergy: 6,
    reputationGain: 1,
    ...FIELD_IMAGES.sales,
  }),
  sideJob({
    id: 'commission-nights',
    title: 'Commission Nights',
    category: 'shift',
    schedule: 'evening',
    commitment: 'medium',
    weeklyPay: 115,
    reputationRequired: 3,
    certifications: ['sales-course'],
    careerField: 'sales-marketing',
    ladderTier: 'skilled',
    trackTags: ['sales', 'commission', 'bridge'],
    nextJobIds: ['sales', 'account-executive'],
    recommendedProgramIds: ['sales-diploma', 'marketing-bachelor'],
    description: 'Evening sales work with real upside if you can keep your energy and your pitch together.',
    weeklyStress: 4,
    weeklyEnergy: 7,
    reputationGain: 2,
    contactId: 'recruiter',
    ...FIELD_IMAGES.sales,
  }),
  sideJob({
    id: 'festival-crew',
    title: 'Festival Crew',
    category: 'seasonal',
    schedule: 'weekend',
    commitment: 'heavy',
    weeklyPay: 170,
    reputationRequired: 1,
    certifications: [],
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    trackTags: ['events', 'promo', 'seasonal'],
    nextJobIds: ['promo-account-assistant', 'sales'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Event-season work with sharp weekly cash and just enough brand exposure to help the sales lane later.',
    weeklyStress: 6,
    weeklyEnergy: 10,
    reputationGain: 1,
    contactId: 'broker',
    seasonMonths: [6, 7, 8],
    ...image('https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80', 'Festival crew working under event lights'),
  }),
  sideJob({
    id: 'pet-sitting',
    title: 'Pet Sitting Loop',
    category: 'freelance',
    schedule: 'flex',
    commitment: 'light',
    weeklyPay: 68,
    reputationRequired: 1,
    certifications: [],
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    trackTags: ['service', 'local', 'neighborhood'],
    nextJobIds: ['retail-floor', 'cafe'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Neighbor-facing service work that pays modestly and still helps you build a softer customer-facing reputation.',
    weeklyStress: 1,
    weeklyEnergy: 2,
    reputationGain: 1,
    contactId: 'recruiter',
    ...image('https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1200&q=80', 'Dog walker with a friendly dog in a city park'),
  }),
  sideJob({
    id: 'night-auditor',
    title: 'Night Auditor Shift',
    category: 'shift',
    schedule: 'evening',
    commitment: 'light',
    weeklyPay: 92,
    reputationRequired: 2,
    certifications: [],
    careerField: 'property-real-estate',
    ladderTier: 'entry',
    trackTags: ['front-desk', 'audit', 'bridge'],
    nextJobIds: ['hotel-front-desk', 'leasing-coordinator'],
    recommendedProgramIds: ['property-operations'],
    description: 'Calmer desk work on slow hotel nights. Better than cleaning, and it bridges neatly into front-desk property roles.',
    weeklyStress: 2,
    weeklyEnergy: 5,
    reputationGain: 1,
    contactId: 'banker',
    ...FIELD_IMAGES.hospitality,
  }),
  sideJob({
    id: 'handyman-helper',
    title: 'Handyman Helper',
    category: 'shift',
    schedule: 'weekend',
    commitment: 'medium',
    weeklyPay: 105,
    reputationRequired: 4,
    certifications: ['landlord-license'],
    careerField: 'property-real-estate',
    ladderTier: 'skilled',
    trackTags: ['maintenance', 'repair', 'bridge'],
    nextJobIds: ['maintenance-helper', 'property-operations-assistant'],
    recommendedProgramIds: ['property-operations', 'real-estate-diploma'],
    description: 'Small repair and turnover help that feeds directly into the property path and contractor relationships.',
    weeklyStress: 3,
    weeklyEnergy: 6,
    reputationGain: 1,
    contactId: 'contractor',
    ...FIELD_IMAGES.tools,
  }),
  sideJob({
    id: 'leasing-runner',
    title: 'Leasing Runner',
    category: 'shift',
    schedule: 'weekend',
    commitment: 'light',
    weeklyPay: 88,
    reputationRequired: 3,
    certifications: ['sales-course'],
    careerField: 'property-real-estate',
    ladderTier: 'skilled',
    trackTags: ['showings', 'leasing', 'bridge'],
    nextJobIds: ['leasing-coordinator', 'tenant-services-assistant'],
    recommendedProgramIds: ['property-operations', 'real-estate-diploma'],
    description: 'Show units, run keys, and keep open-house weekends moving for busy property teams.',
    weeklyStress: 2,
    weeklyEnergy: 4,
    reputationGain: 2,
    contactId: 'broker',
    ...FIELD_IMAGES.property,
  }),
  sideJob({
    id: 'phone-support',
    title: 'Phone Support Queue',
    category: 'shift',
    schedule: 'evening',
    commitment: 'light',
    weeklyPay: 84,
    reputationRequired: 2,
    certifications: [],
    careerField: 'technology-product',
    ladderTier: 'entry',
    trackTags: ['support', 'remote', 'bridge'],
    nextJobIds: ['support-desk-trainee', 'content-ops-assistant'],
    recommendedProgramIds: ['software-apprenticeship'],
    description: 'Low-pay support work, but it is clean, remote-friendly, and much easier to pair with study than a physical shift.',
    weeklyStress: 3,
    weeklyEnergy: 3,
    reputationGain: 1,
    knowledgeGain: 1,
    bankAccountRequired: true,
    ...FIELD_IMAGES.tech,
  }),
  sideJob({
    id: 'remote-qa',
    title: 'Remote QA Sweep',
    category: 'freelance',
    schedule: 'flex',
    commitment: 'light',
    weeklyPay: 102,
    reputationRequired: 5,
    certifications: ['qa-certificate'],
    careerField: 'technology-product',
    ladderTier: 'skilled',
    trackTags: ['qa', 'testing', 'remote'],
    nextJobIds: ['content-ops-assistant', 'product-ops-analyst'],
    recommendedProgramIds: ['software-apprenticeship', 'software-bachelor'],
    description: 'Bug sweeps, regression passes, and cleanup tickets that fit around the rest of the week much better than full client work.',
    weeklyStress: 2,
    weeklyEnergy: 4,
    reputationGain: 1,
    knowledgeGain: 1,
    contactId: 'recruiter',
    bankAccountRequired: true,
    ...FIELD_IMAGES.tech,
  }),
  sideJob({
    id: 'startup-intern',
    title: 'Startup Ops Internship',
    category: 'internship',
    schedule: 'daytime',
    commitment: 'medium',
    weeklyPay: 95,
    reputationRequired: 6,
    certifications: ['coding-bootcamp'],
    careerField: 'technology-product',
    ladderTier: 'specialist',
    trackTags: ['startup', 'ops', 'internship'],
    nextJobIds: ['product-ops-analyst', 'operator'],
    recommendedProgramIds: ['software-bachelor', 'product-masters'],
    description: 'Messy but valuable exposure that trades cash for skill, access, and startup credibility.',
    weeklyStress: 3,
    weeklyEnergy: 5,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'recruiter',
    bankAccountRequired: true,
    ...FIELD_IMAGES.startup,
  }),
  sideJob({
    id: 'freelance-retainer',
    title: 'Freelance Retainer',
    category: 'freelance',
    schedule: 'flex',
    commitment: 'medium',
    weeklyPay: 150,
    reputationRequired: 7,
    certifications: ['coding-bootcamp'],
    careerField: 'technology-product',
    ladderTier: 'specialist',
    trackTags: ['freelance', 'web', 'retainer'],
    nextJobIds: ['junior-developer', 'operator'],
    recommendedProgramIds: ['software-bachelor'],
    description: 'Small weekly client maintenance work that compounds if you can keep it consistent beside everything else.',
    weeklyStress: 3,
    weeklyEnergy: 6,
    reputationGain: 1,
    contactId: 'recruiter',
    ...FIELD_IMAGES.tech,
  }),
  sideJob({
    id: 'market-intern',
    title: 'Market Desk Internship',
    category: 'internship',
    schedule: 'daytime',
    commitment: 'light',
    weeklyPay: 75,
    reputationRequired: 5,
    certifications: ['finance-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'skilled',
    trackTags: ['finance', 'internship', 'markets'],
    nextJobIds: ['finance-associate', 'analyst'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    description: 'Bad pay, useful signal. It sharpens knowledge, grows banker trust, and gives the finance path a real foothold.',
    weeklyStress: 2,
    weeklyEnergy: 4,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'banker',
    bankAccountRequired: true,
    ...FIELD_IMAGES.market,
  }),
  sideJob({
    id: 'tax-season-clerk',
    title: 'Tax Season Clerk',
    category: 'seasonal',
    schedule: 'daytime',
    commitment: 'medium',
    weeklyPay: 128,
    reputationRequired: 4,
    certifications: ['finance-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'skilled',
    trackTags: ['tax', 'finance', 'seasonal'],
    nextJobIds: ['bookkeeper', 'payroll-assistant'],
    recommendedProgramIds: ['accounting-diploma'],
    description: 'A temporary documentation grind that pays decently and strengthens the finance lane during filing season.',
    weeklyStress: 4,
    weeklyEnergy: 5,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'banker',
    seasonMonths: [2, 3, 4],
    bankAccountRequired: true,
    ...FIELD_IMAGES.finance,
  }),
  sideJob({
    id: 'bookkeeping-retainer',
    title: 'Bookkeeping Retainer',
    category: 'freelance',
    schedule: 'flex',
    commitment: 'light',
    weeklyPay: 118,
    reputationRequired: 5,
    certifications: ['bookkeeping-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'specialist',
    trackTags: ['bookkeeping', 'small-business', 'retainer'],
    nextJobIds: ['bookkeeper', 'finance-associate'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    description: 'A few small clients with messy books. It is not glamorous, but it turns finance study into repeatable paid work.',
    weeklyStress: 3,
    weeklyEnergy: 3,
    reputationGain: 2,
    knowledgeGain: 1,
    contactId: 'banker',
    bankAccountRequired: true,
    ...FIELD_IMAGES.finance,
  }),
]

export const GIGS: Gig[] = [
  gig({
    id: 'flyers',
    title: 'Street Flyer Handout',
    payout: 45,
    reputationRequired: 0,
    certifications: [],
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    trackTags: ['promo', 'street', 'entry'],
    nextJobIds: ['promo-account-assistant', 'sales'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Hours on your feet pushing leaflets for barely enough cash to matter, but it is still a first step into promo work.',
    ...image('https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80', 'Promotional worker handing out flyers on a city street'),
  }),
  gig({
    id: 'promo-crew',
    title: 'Promo Crew Setup',
    payout: 72,
    reputationRequired: 1,
    certifications: [],
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    trackTags: ['event', 'promo', 'brand'],
    nextJobIds: ['promo-account-assistant', 'campaign-support'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Unload stands, hang banners, and break everything back down before the client notices the chaos.',
    ...image('https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80', 'Event crew setting up a branded activation space'),
  }),
  gig({
    id: 'market-stall',
    title: 'Weekend Market Stall',
    payout: 165,
    reputationRequired: 3,
    certifications: ['sales-course'],
    careerField: 'sales-marketing',
    ladderTier: 'skilled',
    trackTags: ['sales', 'market', 'closing'],
    nextJobIds: ['sales', 'account-executive'],
    recommendedProgramIds: ['sales-diploma'],
    description: 'Move product, haggle hard, and make a decent one-off side margin while sharpening your sales read in public.',
    ...image('https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1200&q=80', 'Seller working at an outdoor market stall'),
  }),
  gig({
    id: 'delivery',
    title: 'Food Delivery Rush',
    payout: 95,
    reputationRequired: 0,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'entry',
    trackTags: ['delivery', 'courier', 'cash-now'],
    nextJobIds: ['delivery-desk-assistant', 'dispatcher'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'A brutal extra push for quick weekly cash, but it does build real route and timing discipline.',
    ...FIELD_IMAGES.mobility,
  }),
  gig({
    id: 'inventory-count',
    title: 'Inventory Count Night',
    payout: 88,
    reputationRequired: 1,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'entry',
    trackTags: ['inventory', 'warehouse', 'count'],
    nextJobIds: ['stockroom-clerk', 'warehouse'],
    recommendedProgramIds: ['logistics-diploma'],
    description: 'Tedious overnight counting work, but it pays a little better than the true bottom-tier hustles and still feeds the ops ladder.',
    ...image('https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80', 'Retail inventory worker scanning shelves in a store'),
  }),
  gig({
    id: 'bike-courier-loop',
    title: 'Bike Courier Loop',
    payout: 132,
    reputationRequired: 2,
    certifications: [],
    careerField: 'operations-logistics',
    ladderTier: 'skilled',
    trackTags: ['courier', 'route', 'urban'],
    nextJobIds: ['dispatcher', 'local-dispatch-coordinator'],
    recommendedProgramIds: ['route-planning-cert', 'logistics-diploma'],
    description: 'Faster parcel runs around town. Better money if your transport can keep up, and it still counts as logistics experience.',
    ...FIELD_IMAGES.mobility,
  }),
  gig({
    id: 'data-entry-blitz',
    title: 'Data Entry Blitz',
    payout: 118,
    reputationRequired: 2,
    certifications: [],
    careerField: 'finance-accounting',
    ladderTier: 'entry',
    trackTags: ['data-entry', 'clerical', 'finance-adjacent'],
    nextJobIds: ['billing-clerk', 'accounts-clerk'],
    recommendedProgramIds: ['finance-night-school'],
    description: 'A boring admin sprint with a firm deadline and a decent check if you can stay focused.',
    ...FIELD_IMAGES.office,
  }),
  gig({
    id: 'tutoring',
    title: 'Exam Prep Tutoring',
    payout: 185,
    reputationRequired: 5,
    certifications: ['finance-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'specialist',
    trackTags: ['teaching', 'finance', 'knowledge'],
    nextJobIds: ['bookkeeper', 'finance-associate'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    description: 'Solid pay for sharp prep sessions and patient explanations. It signals real command of the material, not just exposure to it.',
    ...image('https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80', 'Tutor helping a student with notes and a laptop'),
  }),
  gig({
    id: 'bookkeeping-sprint',
    title: 'Bookkeeping Cleanup Sprint',
    payout: 208,
    reputationRequired: 6,
    certifications: ['bookkeeping-cert'],
    careerField: 'finance-accounting',
    ladderTier: 'specialist',
    trackTags: ['bookkeeping', 'cleanup', 'small-business'],
    nextJobIds: ['bookkeeper', 'finance-associate'],
    recommendedProgramIds: ['accounting-diploma'],
    description: 'Messy small-business books, hard deadline, decent check if you can tame the spreadsheet pile.',
    ...FIELD_IMAGES.finance,
  }),
  gig({
    id: 'showing-assist',
    title: 'Property Showing Assist',
    payout: 132,
    reputationRequired: 4,
    certifications: ['sales-course'],
    careerField: 'property-real-estate',
    ladderTier: 'skilled',
    trackTags: ['showings', 'property', 'bridge'],
    nextJobIds: ['leasing-coordinator', 'tenant-services-assistant'],
    recommendedProgramIds: ['property-operations', 'real-estate-diploma'],
    description: 'Help stage, open, and reset fast apartment tours for a busy broker schedule.',
    ...FIELD_IMAGES.property,
  }),
  gig({
    id: 'repair-callout',
    title: 'Property Repair Callout',
    payout: 145,
    reputationRequired: 4,
    certifications: ['landlord-license'],
    needsProperty: true,
    careerField: 'property-real-estate',
    ladderTier: 'specialist',
    trackTags: ['repair', 'turnover', 'property'],
    nextJobIds: ['property-operations-assistant', 'assistant-property-manager'],
    recommendedProgramIds: ['real-estate-diploma'],
    description: 'Handle snag lists and keep units market-ready. Useful cash and useful proof that you can manage physical problems.',
    ...FIELD_IMAGES.tools,
  }),
  gig({
    id: 'turnover-reset',
    title: 'Turnover Reset',
    payout: 198,
    reputationRequired: 6,
    certifications: ['landlord-license'],
    needsProperty: true,
    careerField: 'property-real-estate',
    ladderTier: 'specialist',
    trackTags: ['turnover', 'property', 'repair'],
    nextJobIds: ['assistant-property-manager', 'manager'],
    recommendedProgramIds: ['real-estate-diploma', 'property-bachelor'],
    description: 'A fast unit turnover push: cleanup, patching, and making a rental feel marketable again.',
    ...image('https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', 'Apartment interior being reset and cleaned for the next tenant'),
  }),
  gig({
    id: 'freelance',
    title: 'Freelance Web Fix',
    payout: 235,
    reputationRequired: 7,
    certifications: ['coding-bootcamp'],
    careerField: 'technology-product',
    ladderTier: 'specialist',
    trackTags: ['freelance', 'web', 'support'],
    nextJobIds: ['junior-developer', 'operator'],
    recommendedProgramIds: ['software-bachelor'],
    description: 'Patch a landing page, send an invoice, repeat when needed. This is the first tech cash that feels like real market demand.',
    ...FIELD_IMAGES.tech,
  }),
  gig({
    id: 'landing-page-build',
    title: 'Landing Page Build',
    payout: 285,
    reputationRequired: 8,
    certifications: ['coding-bootcamp'],
    careerField: 'technology-product',
    ladderTier: 'manager',
    trackTags: ['build', 'frontend', 'client'],
    nextJobIds: ['junior-developer', 'operator'],
    recommendedProgramIds: ['software-bachelor', 'product-masters'],
    description: 'A cleaner freelance build than emergency fixes, but only if your coding lane is already credible.',
    ...image('https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80', 'Developer building a website on dual monitors'),
  }),
  gig({
    id: 'cms-cleanup',
    title: 'CMS Cleanup Sprint',
    payout: 154,
    reputationRequired: 4,
    certifications: ['support-systems-cert'],
    careerField: 'technology-product',
    ladderTier: 'skilled',
    trackTags: ['cms', 'content-ops', 'cleanup'],
    nextJobIds: ['content-ops-assistant', 'implementation-support'],
    recommendedProgramIds: ['software-apprenticeship'],
    description: 'A short cleanup sprint inside a messy content system. Not glamorous, but perfect bridge work for product ops.',
    ...FIELD_IMAGES.tech,
  }),
  gig({
    id: 'records-archive-sprint',
    title: 'Records Archive Sprint',
    payout: 96,
    reputationRequired: 1,
    certifications: [],
    careerField: 'healthcare-administration',
    ladderTier: 'entry',
    trackTags: ['records', 'archiving', 'admin'],
    nextJobIds: ['records-runner', 'medical-records-clerk'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'A boring but legitimate documentation sprint that gives you a first taste of healthcare admin discipline.',
    ...FIELD_IMAGES.health,
  }),
  gig({
    id: 'patient-call-block',
    title: 'Patient Call Block',
    payout: 124,
    reputationRequired: 3,
    certifications: ['healthcare-admin-cert'],
    careerField: 'healthcare-administration',
    ladderTier: 'skilled',
    trackTags: ['calls', 'patients', 'desk'],
    nextJobIds: ['clinic-reception', 'practice-admin-support'],
    recommendedProgramIds: ['healthcare-admin-diploma'],
    description: 'Work through overdue callbacks and scheduling corrections for a busy clinic office.',
    ...FIELD_IMAGES.health,
  }),
  gig({
    id: 'front-desk-fill',
    title: 'Front Desk Fill-In',
    payout: 142,
    reputationRequired: 4,
    certifications: ['healthcare-admin-cert'],
    careerField: 'healthcare-administration',
    ladderTier: 'skilled',
    trackTags: ['front-desk', 'admin', 'coverage'],
    nextJobIds: ['clinic-reception', 'office-manager-health'],
    recommendedProgramIds: ['healthcare-admin-diploma', 'healthcare-bachelor'],
    description: 'A short coverage block at a clinic desk. It pays better than filing and puts your reputation directly in front of decision makers.',
    ...FIELD_IMAGES.health,
  }),
]

export const COURSES: Course[] = [
  course({
    id: 'sales-course',
    title: 'Sales Foundations Certificate',
    cost: 520,
    reputationRequired: 2,
    careerField: 'sales-marketing',
    ladderTier: 'entry',
    educationTier: 'certificate',
    trackTags: ['sales', 'customer', 'pitch'],
    recommendedProgramIds: ['sales-diploma', 'marketing-bachelor'],
    description: 'A cleaner route into better customer-facing work and lower-tier closing roles.',
    ...FIELD_IMAGES.sales,
  }),
  course({
    id: 'crm-analytics-cert',
    title: 'CRM Analytics Certificate',
    cost: 880,
    reputationRequired: 5,
    careerField: 'sales-marketing',
    ladderTier: 'specialist',
    educationTier: 'certificate',
    trackTags: ['crm', 'analytics', 'growth'],
    recommendedProgramIds: ['marketing-bachelor'],
    description: 'Turns selling and campaign support into something more analytical and much more valuable later on.',
    ...FIELD_IMAGES.market,
  }),
  course({
    id: 'finance-cert',
    title: 'Finance Certificate',
    cost: 980,
    reputationRequired: 4,
    careerField: 'finance-accounting',
    ladderTier: 'skilled',
    educationTier: 'certificate',
    trackTags: ['finance', 'accounting', 'markets'],
    recommendedProgramIds: ['finance-night-school', 'accounting-diploma', 'finance-bachelor'],
    description: 'Builds a real finance lane instead of leaving you stuck reading numbers from the outside.',
    ...FIELD_IMAGES.finance,
  }),
  course({
    id: 'bookkeeping-cert',
    title: 'Bookkeeping Certificate',
    cost: 1240,
    reputationRequired: 5,
    careerField: 'finance-accounting',
    ladderTier: 'specialist',
    educationTier: 'certificate',
    trackTags: ['bookkeeping', 'ledgers', 'small-business'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    description: 'Makes bookkeeping and AP work much easier to land and signals that your finance path is getting serious.',
    ...FIELD_IMAGES.finance,
  }),
  course({
    id: 'payroll-cert',
    title: 'Payroll Systems Certificate',
    cost: 1320,
    reputationRequired: 6,
    careerField: 'finance-accounting',
    ladderTier: 'specialist',
    educationTier: 'certificate',
    trackTags: ['payroll', 'compliance', 'office'],
    recommendedProgramIds: ['accounting-diploma', 'finance-bachelor'],
    description: 'A narrower credential, but a very real one for payroll, controls, and higher-trust finance work.',
    ...FIELD_IMAGES.office,
  }),
  course({
    id: 'landlord-license',
    title: 'Landlord License',
    cost: 760,
    reputationRequired: 4,
    careerField: 'property-real-estate',
    ladderTier: 'skilled',
    educationTier: 'certificate',
    trackTags: ['property', 'leasing', 'regulatory'],
    recommendedProgramIds: ['property-operations', 'real-estate-diploma', 'property-bachelor'],
    description: 'Opens property gigs, field work, and the more serious real-estate jobs.',
    ...FIELD_IMAGES.property,
  }),
  course({
    id: 'property-maintenance-cert',
    title: 'Property Maintenance Systems',
    cost: 1180,
    reputationRequired: 5,
    careerField: 'property-real-estate',
    ladderTier: 'specialist',
    educationTier: 'certificate',
    trackTags: ['maintenance', 'systems', 'property'],
    recommendedProgramIds: ['real-estate-diploma', 'property-bachelor'],
    description: 'Turns repair familiarity into a more credible operations signal for property teams.',
    ...FIELD_IMAGES.tools,
  }),
  course({
    id: 'route-planning-cert',
    title: 'Route Planning Certificate',
    cost: 680,
    reputationRequired: 3,
    careerField: 'operations-logistics',
    ladderTier: 'skilled',
    educationTier: 'certificate',
    trackTags: ['routing', 'logistics', 'dispatch'],
    recommendedProgramIds: ['logistics-diploma', 'operations-bachelor'],
    description: 'A straightforward credential that opens cleaner dispatch work fast.',
    ...FIELD_IMAGES.operations,
  }),
  course({
    id: 'operations-systems-cert',
    title: 'Operations Systems Certificate',
    cost: 1280,
    reputationRequired: 6,
    careerField: 'operations-logistics',
    ladderTier: 'specialist',
    educationTier: 'certificate',
    trackTags: ['operations', 'systems', 'fulfillment'],
    recommendedProgramIds: ['logistics-diploma', 'operations-bachelor', 'operations-masters'],
    description: 'The first formal signal that you can handle throughput, reporting, and systems instead of only raw shifts.',
    ...FIELD_IMAGES.operations,
  }),
  course({
    id: 'coding-bootcamp',
    title: 'Coding Bootcamp Certificate',
    cost: 1680,
    reputationRequired: 6,
    careerField: 'technology-product',
    ladderTier: 'specialist',
    educationTier: 'certificate',
    trackTags: ['coding', 'software', 'career-switch'],
    recommendedProgramIds: ['software-apprenticeship', 'software-bachelor'],
    description: 'A painful but useful jump in technical earning power, especially if you can pair it with a longer formal path later.',
    ...FIELD_IMAGES.tech,
  }),
  course({
    id: 'qa-certificate',
    title: 'Quality Assurance Certificate',
    cost: 980,
    reputationRequired: 4,
    careerField: 'technology-product',
    ladderTier: 'skilled',
    educationTier: 'certificate',
    trackTags: ['qa', 'testing', 'systems'],
    recommendedProgramIds: ['software-apprenticeship', 'software-bachelor'],
    description: 'Gives your testing and support work more legitimacy and makes the tech ladder feel less improvised.',
    ...FIELD_IMAGES.tech,
  }),
  course({
    id: 'support-systems-cert',
    title: 'Support Systems Certificate',
    cost: 860,
    reputationRequired: 3,
    careerField: 'technology-product',
    ladderTier: 'skilled',
    educationTier: 'certificate',
    trackTags: ['support', 'systems', 'ops'],
    recommendedProgramIds: ['software-apprenticeship'],
    description: 'A cheaper bridge into cleaner support and implementation work.',
    ...FIELD_IMAGES.office,
  }),
  course({
    id: 'healthcare-admin-cert',
    title: 'Healthcare Admin Certificate',
    cost: 820,
    reputationRequired: 3,
    careerField: 'healthcare-administration',
    ladderTier: 'skilled',
    educationTier: 'certificate',
    trackTags: ['healthcare', 'admin', 'desk'],
    recommendedProgramIds: ['healthcare-admin-diploma', 'healthcare-bachelor'],
    description: 'Turns desk and records work into a more credible healthcare-office path.',
    ...FIELD_IMAGES.health,
  }),
  course({
    id: 'medical-billing-cert',
    title: 'Medical Billing Certificate',
    cost: 1180,
    reputationRequired: 5,
    careerField: 'healthcare-administration',
    ladderTier: 'specialist',
    educationTier: 'certificate',
    trackTags: ['billing', 'claims', 'healthcare'],
    recommendedProgramIds: ['healthcare-admin-diploma', 'healthcare-bachelor'],
    description: 'A practical credential that cleanly opens better-paid billing and office roles.',
    ...FIELD_IMAGES.health,
  }),
  course({
    id: 'compliance-admin-cert',
    title: 'Compliance Admin Certificate',
    cost: 1540,
    reputationRequired: 7,
    careerField: 'healthcare-administration',
    ladderTier: 'manager',
    educationTier: 'certificate',
    trackTags: ['compliance', 'healthcare', 'governance'],
    recommendedProgramIds: ['healthcare-bachelor', 'healthcare-masters'],
    description: 'Signals that you can handle policy, risk, and regulated office processes instead of only front-desk work.',
    ...FIELD_IMAGES.health,
  }),
]

export const UPGRADES: Upgrade[] = [
  { id: 'scooter', title: 'Secondhand Scooter', cost: 650, description: 'Delivery work pays more because you can take more orders.', ...FIELD_IMAGES.mobility },
  { id: 'toolkit', title: 'Tool Kit', cost: 480, description: 'Renovations cost less and repair gigs pay a little extra.', ...FIELD_IMAGES.tools },
  { id: 'tenant-crm', title: 'Tenant CRM', cost: 900, description: 'Boost rent collection and lower vacancy risk.', ...FIELD_IMAGES.office },
  { id: 'broker-terminal', title: 'Broker Terminal', cost: 1200, description: 'Cuts trading fees and improves dividend income.', ...FIELD_IMAGES.market },
  { id: 'emergency-fund', title: 'Emergency Reserve System', cost: 850, description: 'Tighter budgeting trims your monthly living costs.', ...FIELD_IMAGES.office },
]

export const JOB_MAP = Object.fromEntries(JOBS.map((item) => [item.id, item])) as Record<string, Job>
export const SIDE_JOB_MAP = Object.fromEntries(SIDE_JOBS.map((item) => [item.id, item])) as Record<string, SideJob>
export const GIG_MAP = Object.fromEntries(GIGS.map((item) => [item.id, item])) as Record<string, Gig>
export const COURSE_MAP = Object.fromEntries(COURSES.map((item) => [item.id, item])) as Record<string, Course>
export const UPGRADE_MAP = Object.fromEntries(UPGRADES.map((item) => [item.id, item])) as Record<string, Upgrade>
