import type { PropertyTemplate, TenantProfile } from '../../game/core/types'

export const PROPERTIES: PropertyTemplate[] = [
  {
    id: 'bedsit',
    title: 'Bedsit Flat',
    cost: 3800,
    baseRent: 310,
    upkeep: 75,
    reputationRequired: 0,
    description: 'Small, cheap, and the first step into passive income.',
    imageUrl: 'https://images.unsplash.com/photo-1761199663970-b759a4a74ae3?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Apartment building exterior with many windows and balconies',
    imageCreditLabel: 'Photo by Brother Yoon on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/apartment-building-exterior-with-many-windows-and-balconies-TM8EBHfK0AE',
  },
  {
    id: 'house',
    title: 'Suburban House',
    cost: 9800,
    baseRent: 690,
    upkeep: 145,
    reputationRequired: 4,
    description: 'Reliable family rent with a bit more maintenance.',
    imageUrl: 'https://images.unsplash.com/photo-1760387420081-c79b9f7540d5?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Suburban house with a blue door and trees',
    imageCreditLabel: 'Photo by Millie Sanz on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/a-suburban-house-with-a-blue-door-and-trees-P1C50ZwvZCg',
  },
  {
    id: 'duplex',
    title: 'Duplex',
    cost: 16500,
    baseRent: 1180,
    upkeep: 230,
    reputationRequired: 8,
    description: 'Two doors, better cash flow, twice the headaches.',
    imageUrl: 'https://images.unsplash.com/photo-1753977724360-70e834f05598?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'House exterior with patio and visible extension details',
    imageCreditLabel: 'Photo by Brett Jordan on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/a-house-exterior-with-pipes-and-a-patio-ZFJh10rCxsY',
  },
  {
    id: 'corner-shop',
    title: 'Corner Shop',
    cost: 24800,
    baseRent: 1800,
    upkeep: 350,
    reputationRequired: 12,
    description: 'Commercial rent can change the whole run if you time it right.',
    imageUrl: 'https://images.unsplash.com/photo-1762059811511-3c60908bfe17?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Cafe storefront at dusk',
    imageCreditLabel: 'Photo by Gilbert Ng on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/obriens-irish-sandwich-cafe-storefront-at-dusk-RQOK2V_npks',
  },
  {
    id: 'micro-office',
    title: 'Micro Office Suite',
    cost: 34000,
    baseRent: 2450,
    upkeep: 470,
    reputationRequired: 15,
    description: 'Late-game commercial property with serious upside.',
    imageUrl: 'https://images.unsplash.com/photo-1760246964044-1384f71665b9?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Modern office building exterior at dusk with lights',
    imageCreditLabel: 'Photo by Jonathan Phillips on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/modern-office-building-exterior-at-dusk-with-lights-fTxWB2uCBz8',
  },
]

export const PROPERTY_MAP = Object.fromEntries(PROPERTIES.map((item) => [item.id, item])) as Record<string, PropertyTemplate>

export const TENANT_PROFILES: TenantProfile[] = [
  {
    id: 'professional',
    label: 'Professional tenant',
    description: 'Pays on time, renews often, and keeps the place in good shape.',
    rentModifier: 0.06,
    reliability: 0.88,
    wear: 0.04,
    preferredDistricts: ['midtown', 'heights'],
  },
  {
    id: 'student',
    label: 'Student tenant',
    description: 'Strong occupancy near campus, but higher turnover and more wear.',
    rentModifier: 0.02,
    reliability: 0.71,
    wear: 0.1,
    preferredDistricts: ['campus', 'arts'],
  },
  {
    id: 'family',
    label: 'Family tenant',
    description: 'Steady lease terms and lower churn if the property is maintained well.',
    rentModifier: 0.08,
    reliability: 0.82,
    wear: 0.05,
    preferredDistricts: ['heights', 'midtown'],
  },
  {
    id: 'risky',
    label: 'Risky tenant',
    description: 'Easy to place in weaker markets, but late payments and damage are more common.',
    rentModifier: -0.08,
    reliability: 0.48,
    wear: 0.18,
    preferredDistricts: ['harbor', 'arts'],
  },
  {
    id: 'business',
    label: 'Commercial tenant',
    description: 'Higher rent and longer terms, but they disappear quickly in weak economies.',
    rentModifier: 0.12,
    reliability: 0.76,
    wear: 0.07,
    commercialOnly: true,
  },
]

export const TENANT_PROFILE_MAP = Object.fromEntries(TENANT_PROFILES.map((item) => [item.id, item])) as Record<string, TenantProfile>
