import type { PropertyTemplate, TenantProfile } from '../../game/core/types'

export const PROPERTIES: PropertyTemplate[] = [
  {
    id: 'bedsit',
    title: 'Bedsit Flat',
    cost: 3800,
    baseRent: 310,
    upkeep: 75,
    reputationRequired: 0,
    description: 'Small, cheap, and the first step into passive income.',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80',
    imageAlt: 'Apartment building exterior with repeating windows',
  },
  {
    id: 'house',
    title: 'Suburban House',
    cost: 9800,
    baseRent: 690,
    upkeep: 145,
    reputationRequired: 4,
    description: 'Reliable family rent with a bit more maintenance.',
    imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1400&q=80',
    imageAlt: 'Detached suburban house with a driveway',
  },
  {
    id: 'duplex',
    title: 'Duplex',
    cost: 16500,
    baseRent: 1180,
    upkeep: 230,
    reputationRequired: 8,
    description: 'Two doors, better cash flow, twice the headaches.',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1400&q=80',
    imageAlt: 'Modern duplex-style home with strong curb appeal',
  },
  {
    id: 'corner-shop',
    title: 'Corner Shop',
    cost: 24800,
    baseRent: 1800,
    upkeep: 350,
    reputationRequired: 12,
    description: 'Commercial rent can change the whole run if you time it right.',
    imageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=80',
    imageAlt: 'Small commercial retail interior with product displays',
  },
  {
    id: 'micro-office',
    title: 'Micro Office Suite',
    cost: 34000,
    baseRent: 2450,
    upkeep: 470,
    reputationRequired: 15,
    description: 'Late-game commercial property with serious upside.',
    imageUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80',
    imageAlt: 'Modern office workspace with desks and natural light',
  },
]

export const PROPERTY_MAP = Object.fromEntries(PROPERTIES.map((item) => [item.id, item])) as Record<string, PropertyTemplate>

export const TENANT_PROFILES: TenantProfile[] = [
  {
    id: 'professional',
    label: 'Professional tenant',
    description: 'Pays on time, renews often, and keeps the place in good shape.',
    rentModifier: 0.06,
    reliability: 0.88,
    wear: 0.04,
    preferredDistricts: ['midtown', 'heights'],
  },
  {
    id: 'student',
    label: 'Student tenant',
    description: 'Strong occupancy near campus, but higher turnover and more wear.',
    rentModifier: 0.02,
    reliability: 0.71,
    wear: 0.1,
    preferredDistricts: ['campus', 'arts'],
  },
  {
    id: 'family',
    label: 'Family tenant',
    description: 'Steady lease terms and lower churn if the property is maintained well.',
    rentModifier: 0.08,
    reliability: 0.82,
    wear: 0.05,
    preferredDistricts: ['heights', 'midtown'],
  },
  {
    id: 'risky',
    label: 'Risky tenant',
    description: 'Easy to place in weaker markets, but late payments and damage are more common.',
    rentModifier: -0.08,
    reliability: 0.48,
    wear: 0.18,
    preferredDistricts: ['harbor', 'arts'],
  },
  {
    id: 'business',
    label: 'Commercial tenant',
    description: 'Higher rent and longer terms, but they disappear quickly in weak economies.',
    rentModifier: 0.12,
    reliability: 0.76,
    wear: 0.07,
    commercialOnly: true,
  },
]

export const TENANT_PROFILE_MAP = Object.fromEntries(TENANT_PROFILES.map((item) => [item.id, item])) as Record<string, TenantProfile>
