import type { BusinessTemplate } from '../../game/core/types'

export const BUSINESSES: BusinessTemplate[] = [
  {
    id: 'laundromat',
    title: 'Laundromat',
    cost: 12800,
    baseRevenue: 1650,
    baseExpense: 980,
    reputationRequired: 6,
    description: 'Boring cash flow with decent durability when the neighborhood stays busy.',
    preferredDistricts: ['midtown', 'harbor'],
    imageUrl: 'https://images.unsplash.com/photo-1743527490059-2083f5be9875?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Laundromat interior with washing machines and chairs',
    imageCreditLabel: 'Photo by Mark Hamilton on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/a-sunny-laundromat-interior-with-machines-and-chairs-t6k95Gz1wMw',
  },
  {
    id: 'corner-cafe',
    title: 'Corner Cafe',
    cost: 17400,
    baseRevenue: 2380,
    baseExpense: 1510,
    reputationRequired: 8,
    description: 'Strong upside in active districts, but sentiment and staffing matter more.',
    preferredDistricts: ['arts', 'midtown', 'campus'],
    imageUrl: 'https://images.unsplash.com/photo-1761199664451-0dc5865c7eb4?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Cafe exterior with outdoor seating area',
    imageCreditLabel: 'Photo by Brother Yoon on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/exterior-of-a-cafe-with-outdoor-seating-area-hHskojXGkkc',
  },
  {
    id: 'repair-shop',
    title: 'Repair Shop',
    cost: 21100,
    baseRevenue: 2620,
    baseExpense: 1580,
    reputationRequired: 10,
    description: 'Maintenance-heavy, but a good operator can turn local demand into repeat profit.',
    preferredDistricts: ['harbor', 'midtown'],
    imageUrl: 'https://images.unsplash.com/photo-1752393344237-06b9caf45b1c?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Covered car outside a repair shop',
    imageCreditLabel: 'Photo by Jacob Padilla on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/a-covered-car-sits-outside-a-repair-shop-zAFEEeBZqps',
  },
  {
    id: 'micro-saas',
    title: 'Micro SaaS',
    cost: 28600,
    baseRevenue: 3420,
    baseExpense: 1760,
    reputationRequired: 13,
    description: 'Higher margin and lower wear, but market sentiment and staffing quality matter a lot.',
    preferredDistricts: ['midtown', 'arts', 'heights'],
    imageUrl: 'https://images.unsplash.com/photo-1741453115364-be8703786a03?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=80&w=1400',
    imageAlt: 'Modern office building with a grid-like glass exterior',
    imageCreditLabel: 'Photo by David Underland on Unsplash',
    imageCreditUrl: 'https://unsplash.com/photos/modern-office-building-with-a-grid-like-glass-exterior-KSzU4ipf5dc',
  },
]

export const BUSINESS_MAP = Object.fromEntries(BUSINESSES.map((item) => [item.id, item])) as Record<string, BusinessTemplate>
